### ISSUE TITLE
No Access-Control-Allow-Origin header present on requested resource. File Upload Bug. v2.2.18

### ISSUE THREAD

**Issue by TAProgramming** [parse-community/parse-server#2650] opened 2016-09-04 11:42 UTC
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!
- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.
- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases
- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.
- [x] You have filled out every section below. Issues without sufficient information are more likely to be closed.
## 
### Issue Description

Parse.File does not save. Parse code brings up error of "undefined" and google chrome console shows this error: 

XMLHttpRequest cannot load https://my-server.com/parse/files/Song.mp3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://[app-domain].com' is therefore not allowed access. The response had HTTP status code 413.

I cannot upload either with Gridstore or my GCS Bucket.

My Code (used to work on hosted parse):

```
function UploadFiles() {

    var UploadFile = document.getElementById('SongFile').value;
    var filename = UploadFile.replace(/^.*[\\\/]/, '');
    var fileUploadControl = $('#SongFile')[0];
    if (fileUploadControl.files.length > 0) {
        var file = fileUploadControl.files[0];
        var name = filename;
        UploadSongFile = new Parse.File(name, file, "audio/mpeg");

        } else {
            //File is too small
        }   

    UploadSongFile.save().then(function () {
          alert("Success");
    }, function (error1) {


            $('#Upload').removeClass('loading');


            alert(error1.message);



    });
}
```
### Environment Setup
- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.18 (Yongjhih dev docker image) 
  - Operating System:     Ubuntu 14.04 with Docker image
  - Hardware:             1CPU/1GB RAM
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean

Even though I'm currently using Docker to run Parse Server, I have had the same issue with file upload every time I've installed parse server globally. This is not related to docker.
### Logs/Trace

XMLHttpRequest cannot load https://my-server.com/parse/files/Song.mp3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://[app-domain].com' is therefore not allowed access. The response had HTTP status code 413.

**Comment by flovilmart** [comment] 2016-09-04 17:13
From what I see from the code, it seems that the middleware is properly set: https://github.com/ParsePlatform/parse-server/blob/master/src/ParseServer.js#L267

Can you provide a screenshot of the response headers that you see in your navigator inspector at the time of the request&

**Comment by TAProgramming** [comment] 2016-09-04 19:52
![no access-control-allow-origin](https://cloud.githubusercontent.com/assets/17008848/18233507/51409718-72e1-11e6-98bb-55079250431d.jpg)

Here is a screenshot of my network console (navigator inspector), in google chrome as I'm trying to save a parse.file.
I hope you understand that I've censored my domain names considering my product isn't market ready.
Thank you :)

**Comment by johanarnor** [comment] 2016-09-06 07:22
We are experiencing the exact same issue when upgrading from 2.2.13, but "resolved" the problem by staying on 2.2.17.

**Comment by TAProgramming** [comment] 2016-09-06 17:33
I have had the problem on every version of parse-server I have tried since March 2016. I can't use 2.2.17 because parse dashboard says unauthorised if I don't use "yongjhih/parse-server:dev" when configuring docker.
So I'm stuck with using the latest version of parse-server.

**Comment by flovilmart** [comment] 2016-09-07 16:33
I'll have a look and make sure it's fixed for the next release

**Comment by flovilmart** [comment] 2016-09-19 23:31
Can you try 2.2.21, that should be resolved.

**Comment by flovilmart** [comment] 2016-09-25 18:18
@TAProgramming we just released 2.2.22, can you confirm the issue is gone with the latest version?

**Comment by jmanlapid** [comment] 2016-10-11 19:18
I am experiencing this same issue as well and am using the latest release 2.2.22. https://github.com/ParsePlatform/parse-server/issues/2859

**Comment by flovilmart** [comment] 2017-09-10 18:00
Closing as old and never got feedback on the fix, please open a new issue if it persists on latest parse-server version.

**Closed by flovilmart** 2017-09-10 18:00 UTC
Labels: troubleshooting
