### ISSUE TITLE
containedIn on an array type key

### ISSUE THREAD

**Issue by jeremypiednoel** [parse-community/parse-server#4762] opened 2018-05-14 17:27 UTC
Hi Guys !

### Issue Description

I'm trying to use `containedIn` on an array key : 

```
const array = [1 ,2 ,3];
query.containedIn('arrayKey', array);
```

My key arrayKey is an array in the DB : for instance `[1, 3];`
My issue is the query will return objects where at least one item from array is in arrayKey and not all of them.
I'm not sure if it's the normal behavior.
If it is do you guys know a workaround ? because `containsAll` won't work either.
Thanks for the reading.

### Steps to reproduce

Make a `containedIn` query on array key.

### Environment Setup

- **Server**
  - parse-server version : `2.7.4`
  - Operating System:   ` macOS 10.12.6 (Sierra)`
  - Hardware:             `iMac (Retina 5K, 27-inch, Late 2015)`
  - Localhost or remote server? `Localhost`

#

**Comment by flovilmart** [comment] 2018-05-14 17:47
This is the expected behavior as containedIn operator in mongodb behaves this way. If you’re looking for and exact match, use the equal operator

**Comment by jeremypiednoel** [comment] 2018-05-14 17:49
Thanks @flovilmart i'm not looking for exact match, i'm looking of `arrayKey` is a subarray of `array`

**Comment by flovilmart** [comment] 2018-05-14 17:53
i believe contains all should do the trick, can you provide the logs when running with VERBOSE=1?

**Comment by jeremypiednoel** [comment] 2018-05-14 18:02
I tried with `containsAll` before asking and it looks like it tries to match all `array` with `arrayKey` and not the opposite

here is the verbose 


```
13:56:55 web.1   |  verbose: REQUEST for [GET] /io/classes/Object: {
13:56:55 web.1   |    "where": {
13:56:55 web.1   |      "offers": {
13:56:55 web.1   |        "$all": [
13:56:55 web.1   |          {
13:56:55 web.1   |            "__type": "Pointer",
13:56:55 web.1   |            "className": "Object1",
13:56:55 web.1   |            "objectId": "n2MvEYmqbh"
13:56:55 web.1   |          },
13:56:55 web.1   |          {
13:56:55 web.1   |            "__type": "Pointer",
13:56:55 web.1   |            "className": "Object1",
13:56:55 web.1   |            "objectId": "wR2Ta0KL2R"
13:56:55 web.1   |          }
13:56:55 web.1   |        ]
13:56:55 web.1   |      },
13:56:55 web.1   |      "zipcode": {
13:56:55 web.1   |        "$in": [
13:56:55 web.1   |          "11230",
13:56:55 web.1   |          "11218",
13:56:55 web.1   |        ]
13:56:55 web.1   |      },
13:56:55 web.1   |    },
13:56:55 web.1   |    "limit": 30,
13:56:55 web.1   |    "order": "time"
13:56:55 web.1   |  } method=GET, url=/io/classes/Object, user-agent=node-XMLHttpRequest, Parse/js1.11.1 (NodeJS 9.2.1), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=2521, connection=close, $all=[__type=Pointer, className=Offer, objectId=n2MvEYmqbh, __type=Pointer, className=Offer, objectId=wR2Ta0KL2R], $in=[11230, 11218], limit=30, order=time
13:56:55 web.1   |  verbose: RESPONSE from [GET] /io/classes/Object: {
13:56:55 web.1   |    "response": {
13:56:55 web.1   |      "results": []
13:56:55 web.1   |    }
13:56:55 web.1   |  } results=[]
13:56:55 web.1   |  info: Ran cloud function ------ for user QD8aQ2KCc4 with:
13:56:55 web.1   |    Input: {}
13:56:55 web.1   |    Result: [] functionName=------
13:56:55 web.1   |  verbose: RESPONSE from [POST] /io/functions/------: {
13:56:55 web.1   |    "response": {
13:56:55 web.1   |      "result": []
13:56:55 web.1   |    }
13:56:55 web.1   |  } result=[]


```

**Comment by flovilmart** [comment] 2018-05-14 18:04
You’re matching the zip code or the offers?

**Comment by jeremypiednoel** [comment] 2018-05-14 18:05
offers is my array of `Object1` in my DB and i try to match it with another array

**Comment by flovilmart** [comment] 2018-05-14 18:32
I added a test that should reproduce your issue but it doesn't seem to fail:

https://github.com/parse-community/parse-server/pull/4764

 Can you have a look and check whether this is what you were looking for?

**Comment by jeremypiednoel** [comment] 2018-05-14 18:44
thanks for the test @flovilmart to recreate the case you should request an All with more objects.

so that would be 


```
"requests": [
    {
      "method": "POST",
      "body": {
        "objects": [
          {
            "__type": "Pointer",
            "className": "Object",
            "objectId": "1OtAIeUHLR"
          },
          {
            "__type": "Pointer",
            "className": "Object",
            "objectId": "spsHOyOE5w"
          }
        ]
      },
      "path": "/1/classes/Parent"
    },
    {
      "method": "POST",
      "body": {
        "objects": [
          {
            "__type": "Pointer",
            "className": "Object",
            "objectId": "z16G0O6abX"
          }
        ]
      },
      "path": "/1/classes/Parent"
    },
    {
      "method": "POST",
      "body": {
        "objects": []
      },
      "path": "/1/classes/Parent"
    }
  ]
```

with query 

```
"where": {
    "objects": {
      "$in": [
        {
          "__type": "Pointer",
          "className": "Object",
          "objectId": "1OtAIeUHLR"
        },
        {
          "__type": "Pointer",
          "className": "Object",
          "objectId": "z16G0O6abX"
        },
        {
        "__type": "Pointer",
        "className": "Object",
        "objectId": "spsHOyOE5w"
        }
      ]
    }
  }
```

and the output should be object 1 : `azbzJDOlYE` and object 3 `BIEVwKoBj4` because they are both a subarray of the query

**Comment by flovilmart** [comment] 2018-05-14 18:57
I added an additional test, and both matches as you would expect. Closing now as I can't reproduce the issue with the provided information.

Feel free to open a PR with the failing tests.

**Closed** 2018-05-14 18:57 UTC

**Comment by jeremypiednoel** [comment] 2018-05-14 19:13
Thanks @flovilmart 

here is the case to reproduce 


```js
const objects = [1,2,3,4,5,6,7,8].map((idx) => {
  const obj = new Parse.Object('Object');
  obj.set('key', idx);
  return obj;
});
let parent;
let parent3;

Parse.Object.saveAll(objects).then(() => {
  parent = new Parse.Object('Parent');
  parent.set('objects', objects.slice(0, 3));
  
  const parent2 = new Parse.Object('Parent');
  parent2.set('objects', [objects[1]]);
  
  parent3 = new Parse.Object('Parent');
  parent3.set('objects', objects.slice(1, 4));
  
  return Parse.Object.saveAll([parent, parent2, parent3]);
}).then(() => {
  const query = new Parse.Query('Parent');
  query.containedIn('objects', objects);
  return query.find();
}).then((result) => {
  expect(result[0].id).not.toBeUndefined();
  expect(result[1].id).not.toBeUndefined();
  expect(result[2].id).not.toBeUndefined();
  expect(result.length).toBe(3);
}).then(done).catch(done.fail);

```

**Comment by jeremypiednoel** [comment] 2018-05-14 19:14
so we want to have all parent where `objects` are contained in objects initial array

**Comment by flovilmart** [comment] 2018-05-14 19:35
@jeremypiednoel did you test your case because it works as expected.

**Comment by jeremypiednoel** [comment] 2018-05-14 19:53
Indeed it's working !
That's very weird I probably have a glitch somewhere else in my code.
Thanks a lot @flovilmart

**Comment by flovilmart** [comment] 2018-05-14 19:54
No problem! Good luck!

**Comment by jeremypiednoel** [comment] 2018-05-14 20:08
Ok i found why the key is to add a value in a parent

  const objects = [1,2,3,4,5,6,7,8].map((idx) => {
  const obj = new Parse.Object('Object');
  obj.set('key', idx);
  return obj;
});
let parent;
let parent3;

  Parse.Object.saveAll(objects).then(() => {
    parent = new Parse.Object('Parent');
    parent.set('objects', objects.slice(0, 3));

    let shift = objects.shift();
// parent2 shouldn't be in the result because shift isn't in the initial array anymore 
    const parent2 = new Parse.Object('Parent');
    parent2.set('objects', [objects[1],shift]);

    parent3 = new Parse.Object('Parent');
    parent3.set('objects', objects.slice(1, 4));

    return Parse.Object.saveAll([parent, parent2, parent3]);
  }).then(() => {
    const query = new Parse.Query('Parent');
    console.log(objects);

    query.containedIn('objects', objects);
    return query.find();
  }).then((result) => {
  expect(result[0].id).not.toBeUndefined();
  expect(result[1].id).not.toBeUndefined();
  expect(result[2].id).not.toBeUndefined();
  expect(result.length).toBe(3);
}).then(done).catch(done.fail);

**Comment by flovilmart** [comment] 2018-05-14 20:18
@jeremypiednoel I just tested it again and with `parent2.set('objects', [shift]);` you only get 2 results, which make sense, as shift would remove the 1st object and the query is only on the next objects.

Keeping your code as is, `object[1]` after the shift is still a valid object in the shifted `objects` and returns the proper values.

Again, Everyting is good on parse-server side, you should have a look at your logic somewhere or write unit tests in your project as it is not impossible to reproduce the issue.

**Comment by flovilmart** [comment] 2018-05-14 20:26
it matches because there's at least one matching, not all matching one in the provided array.

If you're using containsAll, that's a different story.

**Comment by jeremypiednoel** [comment] 2018-05-14 20:29
But when i use containsAll it makes sure that all `objects` are in `parent. objects`
How can i make sure that all `parent. objects` are in `objects`

**Comment by jeremypiednoel** [comment] 2018-05-14 20:30
Because if i follow your logic 
This test should success 

```js 
const objects = [1,2,3,4,5,6,7,8].map((idx) => {
  const obj = new Parse.Object('Object');
  obj.set('key', idx);
  return obj;
});
let parent;
let parent3;

Parse.Object.saveAll(objects).then(() => {
  parent = new Parse.Object('Parent');
  parent.set('objects', objects.slice(0, 3));
  
  let shift = objects.shift();
  // parent2 shouldn't be in the result because shift isn't in the initial array anymore 
  const parent2 = new Parse.Object('Parent');
  parent2.set('objects', [objects[1],shift]);
  
  parent3 = new Parse.Object('Parent');
  parent3.set('objects', objects.slice(1, 4));
  
  return Parse.Object.saveAll([parent, parent2, parent3]);
}).then(() => {
  const query = new Parse.Query('Parent');
  query.containsAll('objects', objects);
  return query.find();
}).then((result) => {
  expect(result[0].id).not.toBeUndefined();
  expect(result[1].id).not.toBeUndefined();
  expect(result.length).toBe(2);
}).then(done).catch(done.fail);
```

**Comment by flovilmart** [comment] 2018-05-14 20:32
No it should not because none of the Parent object contains all passed objects.

**Comment by jeremypiednoel** [comment] 2018-05-14 20:33
Ok so my question is how can i make sure that i return object where parent.objects are all contains into the initial array.
And not at least one like `containedIn` does ?

**Comment by jeremypiednoel** [comment] 2018-05-14 21:02
no the contains all make sure full `objects` is in `parent.objects`
I want the opposite  full `parent.objects` is on `objects`

**Comment by flovilmart** [comment] 2018-05-14 21:07
So there’s no operator to achieve that directly it seems. Besides the ‘equalTo’ operator.

**Comment by jeremypiednoel** [comment] 2018-05-14 21:12
When i try with the `equalTo` I have 

```
17:11:40 web.1   |  error: You cannot use [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] as a query parameter. code=141, message=You cannot use [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Objec
17:11:40 web.1   |  >  t],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] as a query parameter.
```

**Comment by jeremypiednoel** [comment] 2018-05-15 17:38
Hey @flovilmart i finally found how to do it using `$nor` and `$elemMatch`.
Do you think i should add the support on parse server and the convenient method on parse JS ?

**Comment by flovilmart** [comment] 2018-05-15 17:40
That’s interesting! Do you have an idea of how it would be named etc before you get started? Perhaps with a PR on the docs first so we can discuss the API for JS and REST?

**Comment by jeremypiednoel** [comment] 2018-05-15 17:43
I would say `arrayContainedIn` ? what do you think ?
