### ISSUE TITLE
Object.save() returns error if afterSave() generates an exception.

### ISSUE THREAD

**Issue by artua** [parse-community/parse-server#4192] opened 2017-09-20 13:55 UTC
### Issue Description
**Cloud Code:**
Object.save() returns error if afterSave() generates an exception. It returns error with no description.
No matter it's a new object or updated.

**REST API:**
Adding object returns {"code":1,"message":"Internal server error."}

### Steps to reproduce
Create simple afterSave() function which returns an exception.
`Parse.Cloud.afterSave("Test", function(request) {
	console.log(ddd); // ddd is not defined
});
`
Create an object:
`curl -X POST -H "X-Parse-Application-Id: **hidden**" -H "Content-Type: application/json" -d '{"key":"value"}' https://api.host.com/parse/classes/Test
`
#### Expected Results
afterSave() should have **no** impact on return value;

**Cloud Code:** success callback, error logged

**REST API:** {"objectId":"FFfWq1I4vM","createdAt":"2017-09-20T13:19:00.077Z"}

#### Actual Outcome
**Cloud Code:**
error callback, error:{}
No errors logged on server side.

**REST API:**
{"code":1,"message":"Internal server error."}

### Environment Setup
parse-server version **2.3.2** - returns internal server error, Cloud Code exception **NOT logged**
parse-server version **2.4.2** - returns internal server error, Cloud Code exception **NOT logged**
  - Operating System: unknown - nodechef.com hosted
  - Hardware: unknown - nodechef.com hosted
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): nodechef.com

- **Database**
  - MongoDB version: nodechef.com hosted
  - Storage engine: nodechef.com hosted
  - Hardware: nodechef.com hosted
  - Localhost or remote server? nodechef.com hosted

### Logs/Trace
**Cloud Code:** no errors logged **!!!**

**REST API:**
```
App1_xyz at process._tickDomainCallback (node.js:481:9) 
at /bundle/node_modules/parse-server/lib/RestWrite.js:104:18 
at RestWrite.runAfterTrigger (/bundle/node_modules/parse-server/lib/RestWrite.js:1043:19) 
at Object.maybeRunTrigger (/bundle/node_modules/parse-server/lib/triggers.js:396:10) 
at /bundle/node_modules/parse-server/lib/triggers.js:417:26 
at /bundle/cloud/main.js:1177:14 
ReferenceError: ddd is not defined 
at process._tickDomainCallback (node.js:481:9) 
at /bundle/node_modules/parse-server/lib/RestWrite.js:104:18 
at RestWrite.runAfterTrigger (/bundle/node_modules/parse-server/lib/RestWrite.js:1043:19) 
at Object.maybeRunTrigger (/bundle/node_modules/parse-server/lib/triggers.js:396:10) 
at /bundle/node_modules/parse-server/lib/triggers.js:417:26 
at /bundle/cloud/main.js:1177:14 
Uncaught internal server error. [ReferenceError: ddd is not defined] ReferenceError: ddd is not defined 
Error generating response. [ReferenceError: ddd is not defined]
```

**Comment by rihadavid** [comment] 2017-10-03 21:58
Yes, duplicate of #3995

**Comment by flovilmart** [comment] 2017-10-23 03:04
Closing as duplicate.

**Closed by flovilmart** 2017-10-23 03:04 UTC
