### ISSUE TITLE
Full Text Return Error Bad Constraint Parse Server Latest Version

### ISSUE THREAD

**Issue by fsoegiono** [parse-community/parse-server#5539] opened 2019-04-26 22:47 UTC
I'm running my code on cloud parse-server latest version 3.3.0 full text search and it seems it does not work for me. I got the following message...

<img width="561" alt="Screen Shot 2019-04-26 at 3 42 07 PM" src="https://user-images.githubusercontent.com/8943566/56840069-68f83680-683a-11e9-8557-c4f208ca66d2.png">

Here's my code:

![Screen Shot 2019-04-26 at 2 09 10 PM](https://user-images.githubusercontent.com/8943566/56840080-757c8f00-683a-11e9-9cd0-c9cbeccfc213.png)

I'm using mlab/mongodb for storing parse data

Any help is much appreciated.

**Comment by dplewis** [comment] 2019-04-26 22:54
Can you post logs, VERBOSE=1?

Here is where $text is https://github.com/parse-community/parse-server/blob/7122ca05c4e29ccf9d1c86ab3864b08508a09915/src/Adapters/Storage/Mongo/MongoTransform.js#L956

**Comment by fsoegiono** [comment] 2019-04-26 23:00
full logs:

<img width="1662" alt="Screen Shot 2019-04-26 at 4 00 21 PM" src="https://user-images.githubusercontent.com/8943566/56840442-6a2a6300-683c-11e9-9c36-6e5328c9aab4.png">

**Comment by fsoegiono** [comment] 2019-04-26 23:07
Full logs:
<img width="1662" alt="Screen Shot 2019-04-26 at 4 00 21 PM" src="https://user-images.githubusercontent.com/8943566/56840619-559a9a80-683d-11e9-9438-02a3c1ad511f.png">

**Comment by dplewis** [comment] 2019-04-26 23:12
I think this happens because you are querying on the User class, I haven't tested it. Try to set your own index in mongo and see what happens or try a different class.

**Comment by fsoegiono** [comment] 2019-04-26 23:15
Tried different classes. Results are still the same

**Comment by dplewis** [comment] 2019-04-26 23:24
Can you debug it? `node_module/parse_server/lib/Adapters/Storage/Mongo/MongoTransform.js`

I'm unable to reproduce this issue.

**Comment by fsoegiono** [comment] 2019-04-27 01:02
I feel like the index did not create one for field that I want to search. I'm not sure

**Comment by dplewis** [comment] 2019-04-27 02:13
I’ll submit a PR shortly. Need to add support for multiple fields also..

Also to fix your index issue in your logs https://github.com/parse-community/parse-server/blob/master/2.3.0.md

You can drop those 3 indexes and the server will build them for you.

**Comment by dblythy** [comment] 2021-09-22 05:33
I'm going to close this one as we have test cases for fullText which are all working on the latest version here:

https://github.com/parse-community/parse-server/blob/8ed94421e69b1d4fde4ec3625a1f4cfbd6d39c2b/spec/ParseQuery.FullTextSearch.spec.js#L34

@fsoegiono as I see you're using `request/response` syntax, I'm assuming the version you're running is quite outdated.

If the error continues after you upgrade to V4.5.0, and perhaps rebuild your text index, feel free to reopen.

**Closed by dblythy** 2021-09-22 05:33 UTC
Labels: :bug: bug
