### ISSUE TITLE
Server crashes when downloading file

### ISSUE THREAD

**Issue by morndawn** [parse-community/parse-server#6167] opened 2019-10-30 09:54 UTC
### Issue Description

Server crashes when multiple people download the same file at the same time

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0
  - Operating System:    Centos7
  - Hardware:             2CPU/512MB
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Aiyun

- **Database**
  - MongoDB version: 4.2.1
  - Storage engine:  WiredTiger Storage Engine
  - Hardware:       2CPU/512MB
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Aiyun

### Logs/Trace

/var/parse/node_modules/parse-server/lib/ParseServer.js:229
          throw err;
          ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:494:11)
    at ServerResponse.header (/var/parse/node_modules/express/lib/response.js:771:10)
    at ServerResponse.contentType (/var/parse/node_modules/express/lib/response.js:599:15)
    at ServerResponse.sendStatus (/var/parse/node_modules/express/lib/response.js:357:8)
    at GridFSBucketReadStream.<anonymous> (/var/parse/node_modules/parse-server/lib/Adapters/Files/GridFSBucketAdapter.js:127:11)
    at GridFSBucketReadStream.emit (events.js:210:5)
    at GridFSBucketReadStream.EventEmitter.emit (domain.js:478:20)
    at __handleError (/var/parse/node_modules/mongodb/lib/gridfs-stream/download.js:420:9)
    at /var/parse/node_modules/mongodb/lib/gridfs-stream/download.js:227:14
    at /var/parse/node_modules/mongodb/lib/operations/execute_operation.js:75:17 {
  code: 'ERR_HTTP_HEADERS_SENT'
}

**Comment by dplewis** [comment] 2019-11-01 18:58
Can you provide steps to reproduce this?

We highly recommend using [AWS S3 Adapter](http://docs.parseplatform.org/parse-server/guide/#configuring-s3adapter). Its cost effective and better supported than GridFS.

**Comment by mtrezza** [comment] 2020-10-28 17:35
I'm closing this it lacks essential information required to investigate the issue. Please follow up on any questions asked and further steps suggested in the thread and we can re-open this issue.

**Closed by mtrezza** 2020-10-28 17:35 UTC
Labels: needs more info

**Comment by baradatbiu** [comment] 2022-09-01 08:17
@morndawn Did you fix it? Because I have the same error when trying to get a video by URL after downloading it(mp4 from android).
