### ISSUE TITLE
Can't install parse-server@2.7.3

### ISSUE THREAD

**Issue by mortezaalizadeh** [parse-community/parse-server#4627] opened 2018-03-10 21:28 UTC
### Issue Description

I am currently using parse@2.7.2. This morning I tried to upgraded my local parse-server to latest version and got following error:

morteza@MORTEZA ~/scripts $ npm install parse-server

> libpq@1.8.7 install /home/morteza/scripts/node_modules/libpq
> node-gyp rebuild

find: ‘/usr/pg*’: No such file or directory
gyp: Call to 'which pg_config || find /usr/bin /usr/local/bin /usr/pg* /opt -executable -name pg_config -print -quit' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/morteza/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-104-generic
gyp ERR! command "/home/morteza/.nvm/versions/node/v9.8.0/bin/node" "/home/morteza/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/morteza/scripts/node_modules/libpq
gyp ERR! node -v v9.8.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/morteza/scripts/package.json'
npm WARN scripts No description
npm WARN scripts No repository field.
npm WARN scripts No README data
npm WARN scripts No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libpq@1.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.8.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/morteza/.npm/_logs/2018-03-10T21_20_12_118Z-debug.log

### Steps to reproduce

npm install -g parse-server

#### Expected Results

parse-server to be installed

#### Actual Outcome

npm is failing to install the parse-server

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.7.3
  - Operating System:     Linux Mint 18 Sarah
  - Hardware:             Running on a PC
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): remote, Heroku

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

morteza@MORTEZA ~/scripts $ npm install parse-server

> libpq@1.8.7 install /home/morteza/scripts/node_modules/libpq
> node-gyp rebuild

find: ‘/usr/pg*’: No such file or directory
gyp: Call to 'which pg_config || find /usr/bin /usr/local/bin /usr/pg* /opt -executable -name pg_config -print -quit' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/morteza/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-104-generic
gyp ERR! command "/home/morteza/.nvm/versions/node/v9.8.0/bin/node" "/home/morteza/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/morteza/scripts/node_modules/libpq
gyp ERR! node -v v9.8.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/morteza/scripts/package.json'
npm WARN scripts No description
npm WARN scripts No repository field.
npm WARN scripts No README data
npm WARN scripts No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libpq@1.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.8.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/morteza/.npm/_logs/2018-03-10T21_20_12_118Z-debug.log

**Comment by flovilmart** [comment] 2018-03-10 21:29
duplicate of #4625

**Closed by flovilmart** 2018-03-10 21:29 UTC
