### ISSUE TITLE
Interpolate objectId and Pointer (as on parse.com)

### ISSUE THREAD

**Issue by awgeorge** [parse-community/parse-server#3711] opened 2017-04-12 23:13 UTC
### Issue Description

Like: #1014, matchesKeyInQuery returns an empty set.

The ACL is set correctly, and can query both records separately. 

### Steps to reproduce

```
where={
  "season": {
    "$select": {
      "key": "objectId",
      "query": {
        "where": {
          "fullIdentifier": "CD117"
        },
        "className": "Season"
      }
    }
  }
}
```

#### Expected Results

The results should be returned

#### Actual Outcome

An empty set is returned

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.6
  - Operating System:    OSX 10.12.1
  - Hardware:             MBP-2015
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 3.2.11
  - Storage engine:  MMAPv1
  - Hardware:       ??
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

```
REQUEST for [GET] /parse/classes/Fixture?where=%7B%22season%22%3A%7B%22%24select%22%3A%7B%22key%22%3A%22objectId%22%2C%22query%22%3A%7B%22where%22%3A%7B%22fullIdentifier%22%3A%22CD117%22%7D%2C%22className%22%3A%22Season%22%7D%7D%7D%7D&include=home%2ChomeResult%2Chome.club%2Chome.ground%2Caway%2CawayResult%2Caway.club%2Cground%2Cseason&limit=1000&order=date: {} method=GET, url=/parse/classes/Fixture?where=%7B%22season%22%3A%7B%22%24select%22%3A%7B%22key%22%3A%22objectId%22%2C%22query%22%3A%7B%22where%22%3A%7B%22fullIdentifier%22%3A%22CD117%22%7D%2C%22className%22%3A%22Season%22%7D%7D%7D%7D&include=home%2ChomeResult%2Chome.club%2Chome.ground%2Caway%2CawayResult%2Caway.club%2Cground%2Cseason&limit=1000&order=date, host=localhost:1337, accept=*/*, x-parse-application-id=[REDACTED], x-parse-client-version=php1.2.2, x-parse-rest-api-key=[REDACTED], 
verbose: RESPONSE from [GET] /parse/classes/Fixture?where=%7B%22season%22%3A%7B%22%24select%22%3A%7B%22key%22%3A%22objectId%22%2C%22query%22%3A%7B%22where%22%3A%7B%22fullIdentifier%22%3A%22CD117%22%7D%2C%22className%22%3A%22Season%22%7D%7D%7D%7D&include=home%2ChomeResult%2Chome.club%2Chome.ground%2Caway%2CawayResult%2Caway.club%2Cground%2Cseason&limit=1000&order=date: {
  "response": {
    "results": []
  }
} results=[]
```

### Related 
#1014  
#3678 ?

**Comment by awgeorge** [comment] 2017-04-23 17:59
@flovilmart - Do you know if the request JSON is still correct? Maybe the keys have changed?

**Comment by flovilmart** [comment] 2017-04-23 18:51
We haven't changed the API.

**Comment by awgeorge** [comment] 2017-04-23 18:54
Can you point me in a direction to investigate further- I stepped through the code, but there was nothing obvious.
---

**Comment by flovilmart** [comment] 2017-04-23 20:06
What SDK are you using?

**Comment by awgeorge** [comment] 2017-04-23 23:19
I'm using the PHP SDK for the main application.

**Comment by awgeorge** [comment] 2017-04-24 01:32
I've checked the JS SDK - same thing occurs.

**Comment by flovilmart** [comment] 2017-04-24 02:10
Is season a pointer?

**Comment by awgeorge** [comment] 2017-04-24 02:41
It is yes.

**Comment by awgeorge** [comment] 2017-04-24 02:58
More context:

```
var season = new Parse.Query("Season");
season.equalTo("fullIdentifier", "CD117");
season.find({
    useMasterKey: true,  
    success: function(Fixtures){
        console.log(Fixtures);
    },
    error: function(e){
        console.log(e);
    }
});
```

Returns an object: `[ ParseObject { _objCount: 0, className: 'Season', id: 'USbmLVfKWW' } ]`

```
var season = new Parse.Query("Season");
season.equalTo("fullIdentifier", "CD117");

var query = new Parse.Query("Fixture");
query.matchesKeyInQuery("objectId", "season", season)
query.find({
    useMasterKey: true,  
    success: function(Fixtures){
        console.log(Fixtures);
    },
    error: function(e){
        console.log(e);
    }
});
```

Returns an empty array.

**Comment by awgeorge** [comment] 2017-04-24 03:23
```
var query = new Parse.Query("Fixture");
query.equalTo("season", new Parse.Object("Season", {id: "USbmLVfKWW"}))
query.find({
    useMasterKey: true,  
    success: function(Fixtures){
        console.log(Fixtures);
    },
    error: function(e){
        console.log(e);
    }
});
```

Correctly returns the data - so I assume, something has happened to `matchesKeyInQuery` whereby it can't search for pointers? It used to be able to on the hosted server.

**Comment by flovilmart** [comment] 2017-04-24 11:11
Alright, I believe I know what's going on. I'll have a look

**Comment by awgeorge** [comment] 2017-04-27 23:37
@flovilmart - Anything I can try to help with? I'm on a short timescale and getting pressure from a client. If you can point me in the direction, I maybe able to create a patch. Thanks - appreciate your efforts, keeping parse update.

**Comment by flovilmart** [comment] 2017-04-27 23:43
Basically, I believe the issue is that when you use matchesKeyInQuery, it will try to match the objectId instead of the full pointer.

**Comment by flovilmart** [comment] 2017-04-27 23:44
To get started, can you open a PR with the failing test?

**Comment by awgeorge** [comment] 2017-04-27 23:45
I'll get on it -

**Comment by flovilmart** [comment] 2017-04-27 23:58
Awesome! Once the test is written, it's gonna be pretty easy to find the underlying issue :)

**Comment by awgeorge** [comment] 2017-04-28 02:32
@flovilmart - Test complete, where should I look next, my friend?

**Comment by flovilmart** [comment] 2017-04-28 02:54
Probably in RestQuery.js but let me check a few things first about your usage of the API, probably something's amiss.

**Comment by awgeorge** [comment] 2017-04-28 03:10
Switched the keys around: `query.matchesKeyInQuery("season", "objectId", season)` same result -

**Comment by awgeorge** [comment] 2017-04-28 03:21
Just checked the PHP code - it seems the keys are supposed to be the other way around so - I've updated the JS test. Sorry about that -

**Comment by awgeorge** [comment] 2017-05-02 22:55
@flovilmart - I'm desperate for a solution as the season starts on Saturday and really need the system to work identically to last year.

So - I've been digging around https://github.com/parse-community/parse-server/blob/025e7a321886becfe48778c152b01dd0cb3fd492/src/Adapters/Storage/Mongo/MongoTransform.js#L535 - Am I warm?

**Comment by flovilmart** [comment] 2017-05-02 23:31
I'll work on a fix, I have a pretty good idea of what's going on.

**Comment by awgeorge** [comment] 2017-05-02 23:33
You would be a life saver -

**Comment by flovilmart** [comment] 2017-05-02 23:51
Did you try to use `matchesQuery("season", seasonQuery)` because it does exactly what you expect it to do.

**Comment by awgeorge** [comment] 2017-05-03 00:05
I would lead with that next time. ahaha 😞 - Good to know. What's the best course of action:

1) update all the SDKs to include a message when `key=="objectId"` (Use `matchesQuery` instead)  
2) update all the SDKs to call `matchesQuery` instead if `key=="objectId"`
3) Fix the server to allow `key=="objectId"`
4) Change the server to internally use the same function as `matchesQuery` if `key=="objectId"`
5) Nothing / maybe update the docs.

**Comment by flovilmart** [comment] 2017-05-03 00:32
None of those, this depends on your data structure, any of each could be valid. Not sure how it was working on Parse.com, if because the target field "season" is a pointer, the objectId's are transformed to a pointer matching.

This is not that the server doesn't allow key=='objectId', this is a valid query when you do:

`query.matchesKeyInQuery("seasonObjectId", "objectId", seasonQuery);`

Where you seasonObjectId column is effectively a string, which is the objectId of a season object.

**Comment by awgeorge** [comment] 2017-05-03 00:40
I see - that makes sense - so there are cases when people just save the ID instead of using a pointer. - Well, now i'm educated. Maybe FB had a fallback in case it returned no results, try a string value match first, then pointer if that failed.

**Comment by flovilmart** [comment] 2017-05-03 00:46
Like I said we could convert those to pointers if the target field is a pointer, did it work before?

**Comment by awgeorge** [comment] 2017-05-03 00:47
It absolutely 100% worked before.

**Comment by flovilmart** [comment] 2017-05-03 00:49
I'm looking for a fix now

**Comment by flovilmart** [comment] 2017-05-03 01:05
TBH' I still would recommend you to change your code, as I can't guarantee when the fix will be released.

**Comment by awgeorge** [comment] 2017-05-03 01:07
@flovilmart - Way ahead of you :) - Thanks so much for your direction, in more ways than one, without you parse would likely fall apart.

**Comment by flovilmart** [comment] 2017-05-03 01:10
Thanks for the kind words, but many other contributors make it work, and without them, I would fall apart.

**Comment by flovilmart** [comment] 2017-05-10 01:05
@awgeorge I changed the nature of the issue as it's not a blocker for the moment, but more a nice to have. Is that fine by you?

**Closed** 2018-09-25 12:13 UTC
Labels: enhancement, wontfix
