### ISSUE TITLE
error: Uncaught internal server error.Cannot destructure property 'clientId' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by LilMoke** [parse-community/parse-server#6856] opened 2020-08-11 13:51 UTC
After updating our Parse Server and Android Client to the latest versions we started to experience this error with our Google users.  Our update included ParseGoogleUtils.

Here is code that appears to show a bug:

What we are seeing is the task is coming back as isCompleted but the user is null.

```
ParseUser.logInWithInBackground(AUTH_TYPE, authData)
	.continueWith { task ->
		when {
			task.isCompleted -> {
				var user = task.result
.
.
.

```

QUESTION:
If the user is null, why is the task completed?

In our searches we found issues #682 which is a similar error.  Because of that post we looked at the server log and see the same error:

error: Uncaught internal server error.Cannot destructure property 'clientId' of 'undefined' as it is undefined.

The other posts do not really give a solution of a way to resolve the issue.  It seems like but turns into a doc discussion or something.

Can someone please explain what has changed and what we need to do?

Thanks for any help.

**Comment by dplewis** [comment] 2020-08-11 14:27
Duplicate: https://github.com/parse-community/parse-server/issues/6852

**Comment by mtrezza** [comment] 2020-08-11 14:34
Thank you for reporting. I'm closing this as it seems to be a duplicate of #6852, let's continue the discussion there.
Feel free to comment if you think this is not a duplicate and we can re-open this issue.

**Closed by mtrezza** 2020-08-11 14:34 UTC
Labels: duplicate, troubleshooting

**Comment by LilMoke** [comment] 2020-08-11 14:36
mtrezza, I believe it is a duplicate but the former has no resolution and I was not sure how to re-open it.

**Comment by SebC99** [comment] 2020-08-11 14:44
@LilMoke Just add an empty object `{}` as google configuration block in auth configuration in Parse Server options

**Comment by LilMoke** [comment] 2020-08-11 14:54
So in my app where I initialize parse I initialize the google adapter like so: ParseGoogleUtils.initialize(googleClientId) and this is how I call log in: 	ParseGoogleUtils.logIn(activity, LogInCallback { parseUser, err ->

So where exactly do I put that empty auth object

**Comment by LilMoke** [comment] 2020-08-11 15:00
Hang on, you said parse server, I will post my server config... sorry
