### ISSUE TITLE
Android Application freezes up completely when using saveEventually() 

### ISSUE THREAD

**Issue by tutorbear** [parse-community/parse-server#6440] opened 2020-02-24 19:39 UTC
### Issue Description
**The client platform is android.**
saveEventually() is suppose to save objects using relations recursively just like saveInBackground does. The logic of my code is very simple and straight forward. I have a logged in user. I create a new ParseObject (Profile) and associate it with the user. Then when I call saveEventually The entire app freezes up. 

### Steps to reproduce

1) Signup and login.
2) Put this code on the onClick listener of a button in android.

      ` Parse user = ParseUser.getCurrentUser();`
       ` //A profile object`
       `profile = new ParseObject("StudentProfile");`
      `  profile.put("user", user);`
      `  profile.put("name", "John");`
       ` profile.setACL(new ParseACL(user));`
        `//Put profile object into user`
       ` user.put("profile",profile);`
        `user.saveEventually();`
### Expected Results

user saved along with new profile object while pointing towards it.

### Actual Outcome

App Freezes

### Environment Setup
  - parse-server version: 3.9.0
  - Hosted on Back4app

### Logs/Trace

Non , App freezes up and stops responding

**Comment by TomWFox** [comment] 2020-02-24 20:09
Hi, if you are going to create multiple identical issues please reference them like this -> parse-community/parse-sdk-android#1007.

**Comment by TomWFox** [comment] 2020-02-24 20:13
If the app stops responding and there is no error on your backend. It's unlikely that this issue is related to Parse Server.

The issue is probably related to the SDK or your use of it, so I'll close this one in favour of the Android SDK issue.

**Closed by TomWFox** 2020-02-24 20:13 UTC

**Comment by tutorbear** [comment] 2020-02-24 20:35
Thanks tom , I am new to issue reporting and did not know about referencing . I'll keep it in mind next time.
