### ISSUE TITLE
Parse Server 2.6.2 is breaking push notification( from 2.4.2)

### ISSUE THREAD

**Issue by handymoby** [parse-community/parse-server#4194] opened 2017-09-20 20:16 UTC
### Issue Description

We upgraded parse server from 2.4.2 to 2.6.2. push notification stopped working(hanging). see log below in parse dashboard
### Steps to reproduce

upgraded to parse server 2.6.2, send a push notification, time out with error logged.
downgraded to 2.4.2, issue disappeared, push can be sent

#### Expected Results

Push sent

#### Actual Outcome

Push not sent, hanging with error logged

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.6.2
  - Operating System:     Linux
  - Hardware:             not known
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Google Cloud

- **Database**
  - MongoDB version: 3.2.16
  - Storage engine:  None
  - Hardware:        not known
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace
parse dashboard is displaying this log.

2017-09-20T19:44:29.969Z - _PushStatus undefined: error while sending push
2017-09-20T19:16:29.040Z - Object not found.
2017-09-20T19:16:29.033Z - Error generating response. ParseError { code: 101, message: 'Object not found.' }

**Comment by flovilmart** [comment] 2017-09-21 11:43
Did you set serverURL in the initialization options?

**Comment by handymoby** [comment] 2017-09-21 21:44
we have been using this in our server.js(express on google app engine)
serverURL: nconf.get('SERVER_URL')
it's been working fine. Should we explicitly set the serverURL in parse server 2.6.2?

thanks

**Comment by flovilmart** [comment] 2017-09-21 21:45
Nah, I was thinking it was an error because now it uses `Parse._request` and it seems that the endpoint may not be available. I'm not sure what's going on there but I'm still investigating.

**Comment by flovilmart** [comment] 2017-09-22 02:12
I've managed to reproduce the issue, it occurs if the serverURL is invalid, for example, the mountPath of parse-server is not the right one etc...

Can you double check that your server URL is formed like

```
http://localhost:[PORT]/[mountPath]
```

where port, is the listening express port and mountPath is the path on which parse-server is mounted?

**Comment by flovilmart** [comment] 2017-09-22 02:49
Closing as PR is opened and you should probably double check your serverURL !

**Closed by flovilmart** 2017-09-22 02:49 UTC
