### ISSUE TITLE
Parse Server Crash when iOS push certificate has expired

### ISSUE THREAD

**Issue by riccardoch** [parse-community/parse-server#3842] opened 2017-05-22 08:27 UTC
**Issue Description**
My development push service certificate has just been expired and Parse Server crashes every time a push is sent.

Parse Server version: 2.4.0
Node version: 6.10.3
Mongo version: 3.2.13

Exception:
```
Error: certificate has expired: 2017-05-19T09:18:22.000Z
    at validateCredentials (/PARSE_SEVER_PATH/node_modules/apn/lib/credentials/validate.js:12:9)
    at /PARSE_SEVER_PATH/node_modules/apn/lib/connection.js:163:5
    at _fulfilled (/PARSE_SEVER_PATH/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/PARSE_SEVER_PATH/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/PARSE_SEVER_PATH/node_modules/q/q.js:816:13)
    at /PARSE_SEVER_PATH/node_modules/q/q.js:624:44
    at runSingle (/PARSE_SEVER_PATH/node_modules/q/q.js:137:13)
    at flush (/PARSE_SEVER_PATH/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by flovilmart** [comment] 2017-05-22 14:21
Just update your certificate.

Closing as this behavior is documented on the apn package.

**Closed by flovilmart** 2017-05-22 14:21 UTC

**Comment by riccardoch** [comment] 2017-05-22 14:23
I know, but I think is not a good solution leaving Parse Server crashing when the certificate has been expired

**Comment by flovilmart** [comment] 2017-05-22 15:02
It's also a duplicate of https://github.com/parse-community/parse-server/issues/3575

In any case, this is not handled in parse-serve but in https://github.com/parse-server-modules/parse-server-push-adapter
