### ISSUE TITLE
fix for PublicApiRouter.js

### ISSUE THREAD

**Issue by Macifier** [parse-community/parse-server#4538] opened 2018-02-01 16:07 UTC
please modify 172 line of PublicApiRouter.js to
    var params = _querystring2.default.stringify({ username: username, token: token, id: config.applicationId, error: err.message, app: config.appName });
because you are sending error object to choose_password params url so it is getting error as empty if you send err.message atleast we can display error on choose_password if it doesn't match password criteria

**Comment by dplewis** [comment] 2018-02-01 16:11
Do you mean this line https://github.com/parse-community/parse-server/blob/master/src/Routers/PublicAPIRouter.js#L159?

Do you want to submit a PR?

**Comment by dplewis** [comment] 2018-02-01 16:27
@Macifier I put this up for grabs as I don't have time right now. @montymxb

**Comment by montymxb** [comment] 2018-02-01 19:23
So the only suggested change here is to the current line:
```js
const params = qs.stringify({username: username, token: token, id: config.applicationId, error:err, app:config.appName});
```
by passing `err.message` instead of just `err`, just to make it clear.

@Macifier your issue is a need for customization right? Can you detail exactly what the existing problem is with the current passing of err? It is an object, but it should be encoded in the url string, or is just ending up completely blank as you mentioned?

**Comment by Macifier** [comment] 2018-02-01 20:20
it is ending up blank yes thats the line i have tested it locally but if we modify it to err.message then it works fine

**Comment by montymxb** [comment] 2018-02-01 22:35
I would be nice to keep the entire error object, or most of it. The error code would also be useful for example. It sounds like the object just needs to be prepped to stringify, surprised it isn't just automatically encoded with the rest of the params.

@Macifier do you think you could put something together to that extend? If you can put up a PR that would be quite helpful. I'm running around at the moment and won't be able to make the change anytime soon myself.

**Comment by paulovitin** [comment] 2018-02-02 17:58
![image](https://user-images.githubusercontent.com/125503/35747575-815f991a-0829-11e8-8c08-74f97444ecac.png)

**Comment by paulovitin** [comment] 2018-02-02 17:59
![image](https://user-images.githubusercontent.com/125503/35747604-9adbffa0-0829-11e8-9fc1-4985916d4371.png)

**Comment by montymxb** [comment] 2018-02-27 02:16
@paulovitin I'm fantastic at getting back to notifications on time! 🤣  (extreme sarcasm...)

Sorry about the wait. 
Something like `JSON.stringify` followed by `urlencode` could do the trick. Then we would be able to pass it a url encoded json string, allowing us to later decode to get the error object back.

**Comment by flovilmart** [comment] 2018-09-27 00:49
ping @paulovitin?

**Comment by paulovitin** [comment] 2018-09-27 00:57
@flovilmart 👀

**Comment by flovilmart** [comment] 2018-09-27 00:58
You mentioned you wanted to help :P that would be nice indeed!

**Comment by paulovitin** [comment] 2018-09-27 01:01
Sure... i will look until the end of this week.. Sorry haha

**Comment by flovilmart** [comment] 2018-09-27 01:01
No rush! it's been sitting there for a while and I came by it :)

**Comment by paulovitin** [comment] 2018-09-30 05:16
Guys, I believe this no make sense. The error object, is a `Parse.Error`, and it has a toString method. The `qs.stringify` makes the conversion correct, and you will receive the JSON object in the error querystring.

If you try:
```js
var query = qs.stringify({ error: new Parse.Error(10, 'Test')});
// returns error%5Bmessage%5D=Teste&error%5Bcode%5D=10

var json = qs.parse(query);
// returns  { error: { message: 'Teste', code: '10' } }
```

If the problem is native errors, like `new Error`, I believe the problem is in another place.

@Macifier would you have any logs?

**Comment by dplewis** [comment] 2019-04-03 17:31
Closing via https://github.com/parse-community/parse-server/pull/5332

**Closed by dplewis** 2019-04-03 17:31 UTC
Labels: good first issue, help wanted, up for grabs
