### ISSUE TITLE
How to use Mongodb v3 index search in Parse Server?

### ISSUE THREAD

**Issue by codetycon** [parse-community/parse-server#6781] opened 2020-07-08 16:16 UTC
Hi All,

I am using Parse Server with Mlab. I have created a `Multikey index` from mlab dashboard. Now I wan to use search in `Cloud Function` of `Parse Server`, but I didn't found any option in Parse Server to run Query and order by on a specific field.

Anyone have idea how we can perform Search and other MOngo V3 queries in parse server?

Thanks

**Comment by mtrezza** [comment] 2020-07-08 17:27
In the [docs](https://docs.parseplatform.org/js/guide/#query-constraints) you can find examples:
```js
// Sorts the results in ascending order by the score field
query.ascending("score");

// Sorts the results in descending order by the score field
query.descending("score");
```

MongoDB will automatically choose an appropriate index. You can find more infos regarding indexing in the [docs](https://docs.parseplatform.org/js/guide/#indexing).

**Comment by codetycon** [comment] 2020-07-09 04:02
> In the [docs](https://docs.parseplatform.org/js/guide/#query-constraints) you can find examples:
> 
> ```js
> // Sorts the results in ascending order by the score field
> query.ascending("score");
> 
> // Sorts the results in descending order by the score field
> query.descending("score");
> ```
> 
> MongoDB will automatically choose an appropriate index. You can find more infos regarding indexing in the [docs](https://docs.parseplatform.org/js/guide/#indexing).

I already implemented this but this searching on only one column , I want to apply search on all columns like firstname, lastname and description and want to order by firstname. I have achieved this by OR query but this query taking long execution time on my 175K records.

ANy solution?

**Comment by mtrezza** [comment] 2020-07-09 04:56
> I want to apply search on all columns like firstname, lastname and description and want to order by firstname.

```js
let query = new Parse.Query("_User");
query.equalTo("firstname", "John");
query.equalTo("lastname", "Doe");
query.descending("firstname");
```

If this is not what you mean, please provide an example data set, your current code, the expected results and the actual results.

**Comment by codetycon** [comment] 2020-07-09 12:42
I don't want an exact match of firstname and lastname

I have a class "Artists". In this class I have few fields (firstname,
lastname, description).

Now I want to search Artist based on the string,

Example: User type `paint` ina  front end form, this will be search in
firstname, lastname and description to see if any entry have "paint" in any
of the three column and want to order on a firstname.

**Comment by mtrezza** [comment] 2020-07-09 14:41
You would have to create the index manually in the DB:
```js
db.Artists.createIndex({
    firstname: "text",
    lastname: "text",
    description: "text"
})
```

Then do a text search as described in the [docs](https://docs.parseplatform.org/js/guide/#queries-on-string-values):
```js
let query = new Parse.Query("Artists");
query.fullText("firstname", "paint");
query.ascending("firstname");
let results = await query.find();
```

If a text index is a compound index, then the search will automatically cover all fields of the text index. This is expected behavior by MongoDB but not explicitly mentioned in the Parse Server docs.

**Comment by codetycon** [comment] 2020-07-09 14:58
Yes I have the custom index, so I just need to write a fulltext query with
the first key (firstname) in the compound index, right?

**Comment by codetycon** [comment] 2020-07-10 06:14
> You would have to create a [text index](https://docs.mongodb.com/manual/core/index-text/) manually in the DB:
> 
> ```js
> db.Artists.createIndex({
>     firstname: "text",
>     lastname: "text",
>     description: "text"
> })
> ```
> 
> Then do a text search as described in the [docs](https://docs.parseplatform.org/js/guide/#queries-on-string-values):
> 
> ```js
> let query = new Parse.Query("Artists");
> query.fullText("firstname", "paint");
> query.ascending("firstname");
> let results = await query.find();
> ```
> 
> If a text index is a compound index, then the search will automatically cover all fields of the text index. This is expected behavior by MongoDB but not explicitly mentioned in the Parse Server docs.
> 
> It makes sense to add this to the docs, a PR would be very welcome.

I have applied this but the search does not returning all the match result in a sorting (firstname ascending) and also lot of search saying no records but we have an search string in the `description` field.

**Comment by mtrezza** [comment] 2020-07-10 12:15
If a query is not working as expected, we need to look at the specifics:
- Parse query code
- records in DB
- index in DB
- expected results
- actual results
- Parse Server log entries
- MongoDB log entries (executed query)

**Comment by codetycon** [comment] 2020-07-12 15:40
It seems to be working, I think indexing was under processing..

**Comment by mtrezza** [comment] 2020-07-12 15:42
Great, would you want to create a PR for the docs and add an example for compound text index? That could certainly help others.

**Comment by codetycon** [comment] 2020-07-12 16:53
Yes, that would be a great to have an detailed documentation, MongoDb have an well described documentation but this is missing in the Parse.

**Comment by mtrezza** [comment] 2020-07-12 16:54
Do you want to add it to the docs?

**Comment by codetycon** [comment] 2020-07-12 16:56
Yes

**Comment by codetycon** [comment] 2020-07-12 17:19
Please also post the link of documentation in this ticket, so user who read this issue can find documentation directly.

**Comment by mtrezza** [comment] 2020-07-12 17:23
You can link to the documentation after you have added it.

**Comment by codetycon** [comment] 2020-07-12 17:27
You mean I need to write a document for this? If yes then where?

**Comment by mtrezza** [comment] 2020-07-12 17:32
> You mean I need to write a document for this? If yes then where?

Yes, that would be very helpful. 🙂 It is quite easy, you can find some guides online how to make a [pull request](https://docs.github.com/en/github/getting-started-with-github/github-glossary#pull-request).

Let me know if you need any help and I will guide you.

**Comment by codetycon** [comment] 2020-07-12 17:51
Thanks for the info, I will create doc for this and push to the repo.

**Comment by mtrezza** [comment] 2020-07-25 23:37
Let me know if you need any help with how to contribute and open a PR 🙂

**Comment by mtrezza** [comment] 2020-07-27 03:07
I'm closing this as it seems to be resolved. Feel free to comment if you have any questions and we can re-open this issue.

Docs issue in https://github.com/parse-community/docs/issues/749

**Closed by mtrezza** 2020-07-27 03:07 UTC
Labels: documentation, troubleshooting

**Comment by elimau** [comment] 2021-08-11 05:40
@mtrezza or anyone,
You mentioned, the solution is doing a db command directly. 
I am using parse sdk js.
How can i get the 'db' object via parse sdk js?
Especially the one that parse has already been initialized by parse client.
