### ISSUE TITLE
Unable to stream Video using PFFile

### ISSUE THREAD

**Issue by wooknight** [parse-community/parse-server#3690] opened 2017-04-05 05:06 UTC
http://stackoverflow.com/questions/43360204/unable-to-view-videos-in-ios-app-uploaded-to-heroku-s3-via-parse-server

I would be grateful for any pointers here

**Comment by ZacharyKhan** [comment] 2017-05-03 11:56
Check #1440, may help your situation.

**Comment by natanrolnik** [comment] 2017-05-04 12:06
Closing as duplicate of #1440, #326, #692, #2127, #1698 and #1973
@wooknight hope you got it working.

**Closed by natanrolnik** 2017-05-04 12:06 UTC

**Comment by wooknight** [comment] 2017-07-09 16:12
@ZacharyKhan 
I did check  #1440 and updated my parse server to 2.3.7 which according to @gfosco does have the updates that I need but it has not solved the issue at all 

 @natanrolnik  
I know it sounds like a duplicate but I have updated my parse server . I have updated my Parse IOS SDK and I still get the same issue . I pinged the original authors if they could document their steps but have not received a response

**Comment by ZacharyKhan** [comment] 2017-07-09 19:17
I was able to get this to work a while ago using amazon S3 to store the video files. Basically store the video as a PFFile and *make sure to set the mime type for MP4*.

Then, when retrieving a video file, get the URL string from the pffile and load the video into your player.

**Comment by wooknight** [comment] 2017-07-10 16:04
@ZacharyKhan
Truly appreciate you taking the time here .  I will try those steps and get back to you

**Comment by ZacharyKhan** [comment] 2017-07-10 16:22
@wooknight no problem. Posting your code/errors also would help :)

**Comment by wooknight** [comment] 2017-07-15 16:18
@ZacharyKhan  . Thank you again . This is the code that uploads the file 

       
 ```
file = [PFFile fileWithData:videoContentData contentType:@"video/mp4"];
        [selectedExperienceObject setObject:file forKey:@"video_comment"];
        MPMoviePlayerController *player = [[MPMoviePlayerController alloc] initWithContentURL:self.videoURL];
        player.shouldAutoplay = NO;

```

This is a file that was uploaded to S3

https://s3-us-west-1.amazonaws.com/speedrate/37c02e3efb521608326fdb6577c92c83_file.mp4

I am still not sure what I am missing here. Thank you for your help

**Comment by flovilmart** [comment] 2017-07-16 14:43
What’s the content type header on the file on S3?

**Comment by wooknight** [comment] 2017-07-16 17:48
Hi Flo,
I believe that the header is set to the correct type from what I read in
the resolution of the previous issues


[image: Inline image 1]

Regards

Ramesh Naidu

**Comment by flovilmart** [comment] 2017-07-16 18:05
Image doesn’t seem uploaded.

**Comment by wooknight** [comment] 2017-07-16 18:23
Thank you for taking the time to help with this

![mp4header](https://user-images.githubusercontent.com/973745/28250267-0749d1e4-6a19-11e7-85eb-597ec8d13d92.png)

This is the file  on S3

https://s3-us-west-1.amazonaws.com/speedrate/4ab48fc8a45f1eee32b477b4ad4152ba_file.mp4

**Comment by flovilmart** [comment] 2017-07-16 18:53
I’m able to open the file in safari (iOS 11) so it should work right from the URL as AVURLAsset in AVPlayer

**Comment by flovilmart** [comment] 2017-07-16 18:55
Or MPMoviePlayerController given that the URL is calid

**Comment by wooknight** [comment] 2017-07-17 06:23
Thanks Flo . I am running this on Heroku so the url that I get back is as follows

http://speedrate.herokuapp.com/parse/files/JouG4uxCS5XxQ8Q7VCH9Z8mqnxbAXh3HkMSoEuHc/47f20cc4d8f1818f6c88fc82b30a3213_file.mp4

and while that URL shows up fine on other browsers , it does not show up in Safari . I tried the equivalent S3 url 
https://s3-us-west-1.amazonaws.com/speedrate/47f20cc4d8f1818f6c88fc82b30a3213_file.mp4
It runs fine in Safari ( and all the other browsers) 

Do I need to replace the URL inside the IOS code ? before playing the video ?

Thanks for your help

**Comment by flovilmart** [comment] 2017-07-23 17:03
You should probably configure parseServer and the S3 adapter for direct access so all URL's will be pointing to S3 directly instead of parse-server.
