### ISSUE TITLE
Bug or feature?

### ISSUE THREAD

**Issue by LilMoke** [parse-community/parse-server#5626] opened 2019-05-30 17:55 UTC
### Issue Description

From our iOS App we are using this call to log in a user:

PFUser.logInWithUsername(inBackground: userEmail, password: userPassword)

But if the user enters their userEmail with a different case it fails to log in.  So is this a bug or is there a way to turn of case sensitive compare for the login?  It would be good if I could pass a case flag of something but I do not see a part for that.

### Steps to reproduce

Create a user, for example: MyNewUser@Yahoo.com then try to log in and enter mynewuser@yahoo.com and it fails to log in.

 
### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [FILL THIS OUT]
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT]

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

**Comment by TomWFox** [comment] 2019-05-30 19:05
Not sure if it is a bug but to avoid this problem you could just have `userEmail.lower`

**Comment by LilMoke** [comment] 2019-05-31 07:41
Yes, but if I do that I will need to also perform a .lower when the user is created and their email is saved, right?



On May 30, 2019, at 3:06 PM, Tom Fox <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure if it is a bug but to avoid this problem you could just have userEmail.lower

**Comment by TomWFox** [comment] 2019-05-31 08:05
That’s right, you could do that in a beforeSave trigger on the `Parse.User` class in your Cloud Code.

**Comment by TomWFox** [comment] 2019-07-06 21:19
I think it makes sense to close this as it’s a duplicate of #3990 and is being worked on in #5634.

**Closed by TomWFox** 2019-07-06 21:19 UTC
Labels: pr submitted
