### ISSUE TITLE
Create FileObject database by default, and track file references in objects

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7067] opened 2020-12-13 08:08 UTC
**Is your feature request related to a problem? Please describe.**
For my servers, I use an afterSaveFile trigger to create a class that I can use to track the files uploaded, so that I can moderate them via Parse Dashboard, as there are multiple classes / locations that reference files. In an afterSave trigger on these classes, if a file is removed, I decrement references on the FileObject class, so I can manually delete FileObjects with 0 references.

**Describe the solution you'd like**
Personally, I see inbuilt file tracking as a feature that should be inbuilt, so developers can be more aware of the content that is uploaded to their Parse Server. It could also allow for easier file cleanup (deleting unreferenced files to save storage space) by creating a simple script to delete FileObjects where reference count = 0.

**Describe alternatives you've considered**
Can already be supported via cloud triggers.

**Additional context**
[-Clean up files](https://github.com/parse-community/parse-server/issues/1023)
[-Cloud code triggers](https://docs.parseplatform.org/cloudcode/guide/#aftersavefile)

**Comment by mtrezza** [comment] 2020-12-15 15:21
Thanks for suggesting.

I am closing this as it looks like a duplicate of https://github.com/parse-community/parse-server/issues/6780. The solution you are proposing seems to be a variant of the solutions discussed there. The original issue seem to be the same, as to how to keep track of and delete unreferenced files.

There is an ongoing discussion about how to implement auto-deletion of unreferenced delete files and how a staged implementation could look like, see https://github.com/parse-community/parse-server/issues/6780#issuecomment-655570076.

If you think this is not a duplicate please feel free to comment and we can re-open this issue.

**Closed by mtrezza** 2020-12-15 15:21 UTC
Labels: :rocket: feature
