### ISSUE TITLE
`select()` with a nested key results in an empty object when a pointer doesn't exist

### ISSUE THREAD

**Issue by pgiguere1** [parse-community/parse-server#4080] opened 2017-08-04 18:57 UTC
### Issue Description

When using `select()` with a nested key on a pointer, e.g. `select("pointerKey.nestedKey")`
and the fetched object doesn't have a pointer set, getting the pointer will result in and empty object rather than `undefined`.

I am experiencing this issue on Heroku, but am not able the reproduce it locally, using the same parse-server and node versions.

### Steps to reproduce

```javascript
var query = new Parse.Query("MyClass");
query.doesNotExist("pointerKey");
query.include("pointerKey");
query.first({
  success: function(myObject) {
  	var pointerObject = myObject.get("pointerKey");
  	console.log(pointerObject); // undefined

  	// Expected behavior
  }
});
```

```javascript
var query = new Parse.Query("MyClass");
query.doesNotExist("pointerKey");
query.include("pointerKey");
query.select("pointerKey.nestedKey"); // This line causes the issue
query.first({
  success: function(myObject) {
  	var pointerObject = myObject.get("pointerKey");
  	console.log(pointerObject); // [object Object]
  	console.log(JSON.stringify(pointerObject)); // "{}"

  	// pointerObject should be undefined but is an empty Object
  }
});
```

#### Expected Results

A pointer that has not been set should return `undefined` when using `get()`.

#### Actual Outcome

An empty object is returned when using `get()`.

### Environment Setup

- **Server**
  - parse-server version: 2.5.3
  - Operating System: Ubuntu 14.04
  - Hardware:  Heroku hobby dyno
  - Localhost or remote server? Remote, Heroku

- **Database**
  - MongoDB version: 3.0.11
  - Storage engine: MMAPv1
  - Hardware:  Shared cluster (AWS 1GB RAM)
  - Localhost or remote server? Remote, mLab

**Comment by promisenxu** [comment] 2017-10-14 22:01
Duplicate of #3999

**Comment by flovilmart** [comment] 2017-10-23 03:08
Closing as duplicate, will be fixed with next release.

**Closed by flovilmart** 2017-10-23 03:08 UTC
