### ISSUE TITLE
http post request to instagram error after upgrade to 4.2.0

### ISSUE THREAD

**Issue by hoffergg** [parse-community/parse-server#6756] opened 2020-06-26 01:58 UTC
### Issue Description

Http Post request to instagram auth API and response 'Invalid platform app' after upgrade parse-server version from 3.0.0 to 4.2.0 parse version from 2.1.0 to 2.12.0

### Steps to reproduce

request:

```
var response = await Parse.Cloud.httpRequest({
                    method: 'POST',
                    url: 'https://api.instagram.com/oauth/access_token',
                    body: {
                        client_id: "123182971515000",
                        client_secret : "ba789hjkjk678789h62105be71b0be2",
                        grant_type:"authorization_code",
                        redirect_uri:"https://thirdapi.onesite.com/insta_auth",
                        code:"codexxxxxxx"
                    }
                });
``` 

### Expected Results

It should not response error after upgrade, Is the post content format changed after upgrade version?

### Actual Outcome

response:

```
"data": {
			"error_type": "OAuthException",
			"code": 400,
			"error_message": "Invalid platform app"
		}

```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.2.0 with parse 2.12.0
  - Operating System:     Linux
  - Hardware:             aws ec2
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS

- **Database**
  - MongoDB version: 3.6
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Mongodb Altlas

**Comment by mtrezza** [comment] 2020-07-03 14:16
Maybe related to https://github.com/parse-community/parse-server/issues/6728.

**Comment by mtrezza** [comment] 2020-07-03 14:18
Can you try using the new URL as described in #6728 and see if it works?

**Comment by mtrezza** [comment] 2020-07-07 15:24
I'm closing this as duplicate of #6728, feel free to comment if you have any questions and we can re-open this issue.

**Closed by mtrezza** 2020-07-07 15:24 UTC
Labels: duplicate
