### ISSUE TITLE
Some Push Notifications stuck in SENDING state

### ISSUE THREAD

**Issue by sandratraraza** [parse-community/parse-server#3562] opened 2017-02-24 14:14 UTC
### Issue Description

I've recently moved my Parse Server instance to Heroku. I've put my push logic in Cloud Code instead of using client push and I can send and receive push notifications.

My issue is that the status of the push object is stuck at SENDING in Parse Dashboard ("status": "running" on the mongo object) when one of the pushes can't be delivered to an installation.

Example: I send a push to a list of users, but some of them have an installation with no deviceToken configured. Those with a deviceToken receive the push, but the others don't. 

That's an expected result, but the push status will stay forever in the SENDING state and I'm not sure if I should worry about it or not.

Note: The push status is changed correctly to SENT if all the Installations have a deviceToken and the number of push sent matches the number of push delivered. Also this behaviour did not occurred when I was using client push.

### Steps to reproduce

Send a push to one or more installations with some correctly configured and some with no deviceToken.

#### Expected Results

Those with a deviceToken receive the push, but the others don't. 
The push status change to something other  than "running" even if some failed.

#### Actual Outcome

The push object is stuck forever at SENDING in Parse Dashboard ("status": "running" on the mongo object) even is some notifications were delivered.

I'm not sure if this is a big issue and if I should worry about the server trying to send pushes indefinitely.

### Environment Setup

- **Server**
  - parse-server version  : 2.3.5
  - Hardware: Standard-1x (512 MB)
  - Localhost or remote server?: Heroku

- **Database**
  - MongoDB version: 3.0.14
  - Hardware:  Shared Cluster
  - Localhost or remote server? mLab

### Logs/Trace
Example: 3 pushes sent, 1 device received it, 2 failed because of missing deviceToken. Push object now in sending state forever.
```
2017-02-24T13:59:29.004277+00:00 app[web.1]: [32minfo[39m: Ran cloud function sendPushToRecipients for user xVOydE7ugH with:
2017-02-24T13:59:29.004293+00:00 app[web.1]:   Input: {"recipients":["dpVQ9ZQypH","Vs3OADhHnS"],"data":{"alert":"test.","NTYPE":"NEW","badge":1,"sound":"default"},"appVersion":"1"}
2017-02-24T13:59:29.004295+00:00 app[web.1]:   Result: "Push Sent!" functionName=sendPushToRecipients, recipients=[dpVQ9ZQypH, Vs3OADhHnS], alert=test., NTYPE=NEW, badge=1, sound=default, appVersion=519, user=xVOydE7ugH
```

### _PushStatus object

```
{
    "_id": "ZieiF3w31X",
    "pushTime": "2017-02-24T13:59:28.981Z",
    "query": "{\"currentProfile\":{\"$inQuery\":{\"where\":{\"objectId\":{\"$in\":[\"dpVQ9ZQypH\",\"Vs3OADhHnS\"]}},\"className\":\"Profile\"}},\"appVersion\":\"1\"}",
    "payload": "{\"alert\":\"test",\"NTYPE\":\"NEW\",\"badge\":1,\"sound\":\"default\"}",
    "source": "rest",
    "status": "running",
    "numSent": 1,
    "pushHash": "882c51079dfab452aed1f146fedb37a2",
    "_wperm": [],
    "_rperm": [],
    "_acl": {},
    "_created_at": {
        "$date": "2017-02-24T13:59:28.981Z"
    },
    "_updated_at": {
        "$date": "2017-02-24T13:59:29.066Z"
    },
    "count": 3,
    "sentPerType": {
        "ios": 1
    }
}
```

### Cloud Code

```
Parse.Cloud.define("sendPushToRecipients", function(request, response) {
  var profileQuery = new Parse.Query("Profile");
  profileQuery.containedIn("objectId", request.params.recipients);
  var installationQuery = new Parse.Query(Parse.Installation);
  installationQuery.matchesQuery("currentProfile", profileQuery);
  installationQuery.equalTo("appVersion", request.params.appVersion);
  
  Parse.Push.send({
    expiration_interval:600,
    where: installationQuery,
     data: request.params.data
    }, {
      success: function() {
        response.success("Push Sent!");
      },
      error: function(error) {
        response.error("Push failed: " + error);
      },
      useMasterKey: true
    });
});
```

**Comment by adirgan** [comment] 2017-02-24 18:01
@flovilmart It's the same problem that I raised in #3080

**Comment by iOSassou** [comment] 2017-02-24 18:17
@adirgan Yes, it seems to be the same issue. My Parse Dashboard push page is very similar: the push status is changed correctly to SENT only if all the _Installation objects targeted by the push have a deviceToken. No matter if it's sent to a channel or specific recipients.

From what I've read, is it safe to assume that all the push notifications that have an audience (with valid deviceToken) are actually sent anyway and that it is just an issue with Parse Server not updating _PushStatus correctly because of the faulty _Installation objects?

I'm worried that this SENDING state means some performance issue or something bad with the server. If it is just a state update issue, I can live with that for now.

**Comment by adirgan** [comment] 2017-02-24 18:20
@iOSassou  Do not worry that the push messages arrive without problem and does not affect the performance at all, it is only an error to update the status.

**Comment by iOSassou** [comment] 2017-02-24 18:25
@adirgan Thank you

**Comment by flovilmart** [comment] 2017-02-24 18:34
@adirgan sorry, I believe the ball was dropped on my side on that... 🙇 I need to investigate further. But the state reporting has proven to be quite unreliable in general :/

**Comment by adirgan** [comment] 2017-02-24 18:36
@flovilmart Do not worry, while the problem is only visual and not performance is fine.

**Comment by iOSassou** [comment] 2017-02-24 18:58
@flovilmart @adirgan Yes. As long as it is not really affecting the app, I think it's fine (maybe just a bit confusing).

**Comment by flovilmart** [comment] 2017-02-24 19:05
Yeah that should be fixed however :/ that's clearly a regression

**Comment by felipemobile** [comment] 2017-03-13 13:47
@flovilmart Have found the same issue here after upgrading to the latest version. 
Any clues in how to solve that?

**Comment by flovilmart** [comment] 2017-03-14 13:16
Need to add a small check to exclude installations without deviceToken from the query

**Comment by jeacott1** [comment] 2017-03-15 01:48
upgrade to apn 2.x is really the only solution for proper tracking.

**Comment by flovilmart** [comment] 2017-03-15 01:49
Also there is a bug that I uncovered that improperly forwards the deviceType on successful pushes.

**Comment by felipemobile** [comment] 2017-03-15 12:45
@flovilmart All iOS pushes are not being send, need to downgrade to Parse-Server 2.3.1 to get it working properly.

**Comment by flovilmart** [comment] 2017-03-15 12:58
@felipemobile are they not sent or just marked 'sending'?

**Comment by felipemobile** [comment] 2017-03-15 13:44
Not sent @flovilmart

**Comment by felipemobile** [comment] 2017-03-15 13:45
Maybe a conflict after the #3264, #3080 improvements?

**Comment by flovilmart** [comment] 2017-03-15 14:34
Uhm, not sent is more problematic than just not marked as Sent, can you provide more details, logs etc... to debug that issue? There was an underlying bug in the push adapter that prevented the push status to be properly reported.

**Comment by flovilmart** [comment] 2017-03-15 14:50
Sending a single push don't seem to cause the issue

**Comment by felipemobile** [comment] 2017-03-15 14:52
@flovilmart do you need any special type of log to debug that issue?

**Comment by flovilmart** [comment] 2017-03-15 16:20
Setting VERBOSE=1 should log all see https://github.com/parse-server-modules/parse-server-push-adapter/blob/master/src/index.js

**Comment by felipemobile** [comment] 2017-03-15 17:16
`2017-03-15T17:03:34.104Z - _PushStatus H5qbJ5SSkF: sent push! 0 success, 60 failures
2017-03-15T17:03:34.054Z - _PushStatus H5qbJ5SSkF: sending push to 60 installations
2017-03-15T17:03:34.043Z - RESPONSE from [POST] /app/push: {
  "headers": {
    "X-Parse-Push-Status-Id": "H5qbJ5SSkF"
  },
  "response": {
    "result": true
  }
}
2017-03-15T17:03:34.029Z - REQUEST for [POST] /app/push: {
  "data": {
    "alert": "Morning. This is a test."
  },
  "where": {
    "deviceType": {
      "$in": [
        "ios"
      ]
    }
  }
}
2017-03-15T17:03:10.895Z - RESPONSE from [GET] /app/schemas: {
  "response": {
    "results": [
      {
        "className": "_Installation",
        "fields": {
          "objectId": {
            "type": "String"
          },
          "createdAt": {
            "type": "Date"
          },
          "updatedAt": {
            "type": "Date"
          },
          "ACL": {
            "type": "ACL"
          },
          "installationId": {
            "type": "String"
          },
          "deviceToken": {
            "type": "String"
          },
          "channels": {
            "type": "Array"
          },
          "deviceType": {
            "type": "String"
          },
          "pushType": {
            "type": "String"
          },
          "GCMSenderId": {
            "type": "String"
          },
          "timeZone": {
            "type": "String"
          },
          "localeIdentifier": {
            "type": "String"
          },
          "badge": {
            "type": "Number"
          },
          "appVersion": {
            "type": "String"
          },
          "appName": {
            "type": "String"
          },
          "appIdentifier": {
            "type": "String"
          },
          "parseVersion": {
            "type": "String"
          },
          "email": {
            "type": "String"
          },
          "nome": {
            "type": "String"
          }
        },
        "classLevelPermissions": {
          "find": {
            "*": true
          },
          "get": {
            "*": true
          },
          "create": {
            "*": true
          },
          "update": {
            "*": true
          },
          "delete": {
            "*": true
          },
          "addField": {
            "*": true
          }
        }
      },
      {
        "className": "_Role",
        "fields": {
          "objectId": {
            "type": "String"
          },
          "createdAt": {
            "type": "Date"
          },
          "updatedAt": {
            "type": "Date"
          },
          "ACL": {
            "type": "ACL"
          },
          "name": {
            "type": "String"
          },
          "users": {
            "type": "Relation",
            "targetClass": "_User"
          },
          "roles": {
            "type": "Relation",
            "targetClass": "_Role"
          }
        },
        "classLevelPermissions": {
          "find": {
            "*": true
          },
          "get": {
            "*": true
          },
          "create": {
            "*": true
          },
          "update": {
            "*": true
          },
          "delete": {
            "*": true
          },
          "addField": {
            "*": true
          },
          "readUserFields": [],
          "writeUserFields": []
        }
      },
      {
        "className": "_User",
        "fields": {
          "objectId": {
            "type": "String"
          },
          "createdAt": {
            "type": "Date"
          },
          "updatedAt": {
            "type": "Date"
          },
          "ACL": {
            "type": "ACL"
          },
          "username": {
            "type": "String"
          },
          "password": {
            "type": "String"
          },
          "email": {
            "type": "String"
          },
          "emailVerified": {
            "type": "Boolean"
          },
          "authData": {
            "type": "Object"
          },
          "accountType": {
            "type": "String"
          },
          "avulso": {
            "type": "Object"
          },
          "acesso_total": {
            "type": "String"
          },
          "acessos_simultaneos": {
            "type": "String"
          }
        },
        "classLevelPermissions": {
          "find": {
            "*": true
          },
          "get": {
            "*": true
          },
          "create": {
            "*": true
          },
          "update": {
            "*": true
          },
          "delete": {
            "*": true
          },
          "addField": {
            "*": true
          },
          "readUserFields": [],
          "writeUserFields": []
        }
      },
      {
        "className": "_Session",
        "fields": {
          "objectId": {
            "type": "String"
          },
          "createdAt": {
            "type": "Date"
          },
          "updatedAt": {
            "type": "Date"
          },
          "ACL": {
            "type": "ACL"
          },
          "restricted": {
            "type": "Boolean"
          },
          "user": {
            "type": "Pointer",
            "targetClass": "_User"
          },
          "installationId": {
            "type": "String"
          },
          "sessionToken": {
            "type": "String"
          },
          "expiresAt": {
            "type": "Date"
          },
          "createdWith": {
            "type": "Object"
          },
          "device": {
            "type": "String"
          }
        },
        "classLevelPermissions": {
          "find": {
            "*": true
          },
          "get": {
            "*": true
          },
          "create": {
            "*": true
          },
          "update": {
            "*": true
          },
          "delete": {
            "*": true
          },
          "addField": {
            "*": true
          }
        }
      },
      {
        "className": "TokenStorage",
        "fields": {
          "objectId": {
            "type": "String"
          },
          "createdAt": {
            "type": "Date"
          },
          "updatedAt": {
            "type": "Date"
          },
          "ACL": {
            "type": "ACL"
          },
          "user": {
            "type": "Pointer",
            "targetClass": "_User"
          },
          "accountId": {
            "type": "String"
          },
          "access_token": {
            "type": "String"
          }
        },
        "classLevelPermissions": {
          "find": {
            "*": true
          },
          "get": {
            "*": true
          },
          "create": {
            "*": true
          },
          "update": {
            "*": true
          },
          "delete": {
            "*": true
          },
          "addField": {
            "*": true
          }
        }
      }
    ]
  }
}

2017-03-15T17:03:10.890Z - REQUEST for [GET] /app/schemas: {}
2017-03-15T17:03:10.466Z - RESPONSE from [GET] /app/serverInfo: {
  "response": {
    "features": {
      "globalConfig": {
        "create": true,
        "read": true,
        "update": true,
        "delete": true
      },
      "hooks": {
        "create": true,
        "read": true,
        "update": true,
        "delete": true
      },
      "cloudCode": {
        "jobs": true
      },
      "logs": {
        "level": true,
        "size": true,
        "order": true,
        "until": true,
        "from": true
      },
      "push": {
        "immediatePush": {
          "android": {
            "senderId": "{REMOVED}",
            "apiKey": "{REMOVED}"
          },
          "ios": [
            {
              "pfx": "../push-certs/PushDevCertificate.p12",
              "bundleId": "com.app",
              "production": false
            },
            {
              "pfx": "../push-certs/PushProdCertificate.p12",
              "bundleId": "com.app",
              "production": true
            }
          ]
        },
        "scheduledPush": false,
        "storedPushData": {
          "android": {
            "senderId": "{REMOVED}",
            "apiKey": "{REMOVED}"
          },
          "ios": [
            {
              "pfx": "../push-certs/PushDevCertificate.p12",
              "bundleId": "com.app",
              "production": false
            },
            {
              "pfx": "../push-certs/PushProdCertificate.p12",
              "bundleId": "com.app",
              "production": true
            }
          ]
        },
        "pushAudiences": false
      },
      "schemas": {
        "addField": true,
        "removeField": true,
        "addClass": true,
        "removeClass": true,
        "clearAllDataFromClass": true,
        "exportClass": false,
        "editClassLevelPermissions": true,
        "editPointerPermissions": true
      }
    },
    "parseServerVersion": "2.3.6"
  }
}

2017-03-15T17:03:04.824Z - REQUEST for [GET] /app/serverInfo: {}
2017-03-15T17:02:42.712Z - Support key pairs Map {}
2017-03-15T17:02:42.701Z - Support key pairs Map {}
2017-03-15T17:02:42.695Z - Support key pairs Map {}
2017-03-15T17:02:42.689Z - Support key pairs Map {}
2017-03-15T17:02:42.682Z - Support key pairs Map {}
2017-03-15T17:02:42.678Z - Support key pairs Map {}
2017-03-15T17:02:42.672Z - Support key pairs Map {}
2017-03-15T17:02:42.665Z - Support key pairs Map {}
2017-03-15T17:02:42.658Z - Support key pairs Map {}
2017-03-15T17:02:42.640Z - Support key pairs Map {}`

**Comment by felipemobile** [comment] 2017-03-15 23:11
@flovilmart I've confirmed! This bug was introduced in the parse-server 2.3.3, maybe it's related to #3264 improvement.

**Comment by flovilmart** [comment] 2017-03-15 23:13
@felipemobile I know the bug is here, however I'm not sure the push are not delivered

**Comment by felipemobile** [comment] 2017-03-15 23:21
I've done a very simple and basic test:

**Works (Push sent 1)**
```
$ npm install parse-server@2.3.2
$ npm start index.js
```

**Not working (Push sent 0)**
```
$ npm install parse-server@2.3.3
$ npm start index.js
```

**Comment by flovilmart** [comment] 2017-03-15 23:22
yeah but are they delivered on the device? that doesn't really help here.

**Comment by felipemobile** [comment] 2017-03-15 23:28
Yeap, they are delivered only when using parse-server 2.3.2 or lower.

**Comment by felipemobile** [comment] 2017-03-15 23:36
Please, check this log:

```
/app/push: {
  "data": {
    "alert": "Teste"
  },
  "where": {
    "deviceToken": "3ac4dbf3bc1c73e2ec2542cb183f3b12e516e38cfccc2a607c64dbe05b45a413",
    "deviceType": {
      "$in": [
        "ios"
      ]
    }
  }
} method=POST, url=/app/push, x-real-ip=172.31.33.54, x-forwarded-for=177.159.215.149, 172.31.33.54, x-nginx-proxy=true, host=sandbox.app.com.br, connection=close, content-length=331, accept=*/*, accept-encoding=gzip, deflate, br, accept-language=pt,en-US;q=0.8,en;q=0.6, content-type=text/plain, dnt=1, origin=https://dashboard.app.com.br, referer=https://dashboard.app.com.br/apps/Di%C3%A1rio%20do%20Par%C3%A1/push/new, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36, x-forwarded-port=443, x-forwarded-proto=https, alert=Teste, deviceToken=3ac4dbf3bc1c73e2ec2542cb183f3b12e516e38cfccc2a607c64dbe05b45a413, $in=[ios]
verbose: RESPONSE from [POST] /app/push: {
  "headers": {
    "X-Parse-Push-Status-Id": "CvtA31WMJq"
  },
  "response": {
    "result": true
  }
} X-Parse-Push-Status-Id=CvtA31WMJq, result=true
verbose: _PushStatus CvtA31WMJq: sending push to 1 installations

ERR! parse-server-push-adapter APNS no qualified connections for com.app 3ac4dbf3bc1c73e2ec2542cb183f3b12e516e38cfccc2a607c64dbe05b45a413
verbose: _PushStatus CvtA31WMJq: sent push! 0 success, 1 failures
```

**Comment by flovilmart** [comment] 2017-03-15 23:37
So it reaches correctly the adapter but the connection is not found, and he status is not reported as failed. Can you check with a valid connection?

**Comment by felipemobile** [comment] 2017-03-15 23:43
@flovilmart This is a valid connection, changing to parse-server 2.3.2 works perfectly.

`$ npm install parse-server@2.3.2`

```
verbose: REQUEST for [POST] /app/push: {
  "data": {
    "alert": "Teste"
  },
  "where": {
    "deviceToken": "3ac4dbf3bc1c73e2ec2542cb183f3b12e516e38cfccc2a607c64dbe05b45a413",
    "deviceType": {
      "$in": [
        "ios"
      ]
    }
  }
} method=POST, url=/app/push, x-real-ip=172.31.18.105, x-forwarded-for=177.159.215.149, 172.31.18.105, x-nginx-proxy=true, host=sandbox.app.com.br, connection=close, content-length=331, accept=*/*, accept-encoding=gzip, deflate, br, accept-language=pt,en-US;q=0.8,en;q=0.6, content-type=text/plain, dnt=1, origin=https://dashboard.app.com.br, referer=https://dashboard.app.com.br/apps/Di%C3%A1rio%20do%20Par%C3%A1/push/new, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36, x-forwarded-port=443, x-forwarded-proto=https, alert=Teste, deviceToken=3ac4dbf3bc1c73e2ec2542cb183f3b12e516e38cfccc2a607c64dbe05b45a413, $in=[ios]
verbose: RESPONSE from [POST] /app/push: {
  "headers": {
    "X-Parse-Push-Status-Id": "cK2bS1vwCx"
  },
  "response": {
    "result": true
  }
} X-Parse-Push-Status-Id=cK2bS1vwCx, result=true
verbose: sending push to 1 installations
verbose: sent push! 1 success, 0 failures
```

**Comment by flovilmart** [comment] 2017-03-15 23:48
The adapter says the opposite, which is odd.

**Comment by felipemobile** [comment] 2017-03-16 00:11
In some way it's not clustering the devices per connections

parse-server-push-adapter/APNS.js

```
110     let qualifiedConnIndexs = chooseConns(this.conns, device);
111	  if (qualifiedConnIndexs.length == 0) {
```

Maybe a issue in the adapter?

src/Adapters/Push/PushAdapter.js

```
export class PushAdapter {

 -  send(devices, installations, pushStatus) { }
 +  send(body: any, installations: any[], pushStatus: any): ?Promise<*> {}
```

**Comment by flovilmart** [comment] 2017-03-16 00:22
I would think that, adapter went from 1.1.0 to 1.2.0, need to check what changed in between and why the connection grouping is bad

**Comment by felipemobile** [comment] 2017-03-16 00:30
I forgot to point that Android stopped working either.

**Comment by flovilmart** [comment] 2017-03-16 00:44
Uhm. It gets better and better!

**Comment by felipemobile** [comment] 2017-03-16 00:47
What's the best way to debug this issue? I need to fix it before moving forward on the pending Parse-Dashboard improvements.

**Comment by felipemobile** [comment] 2017-03-16 00:52
I read about a SQS adapter that could allow us to set a work queue to delivery a high number of push messages. To provide more context I've 5 apps using Parse-Server with more than 80k valid installations. 

Our Parse-Server API is under a loadbalancer with two EC2 instances attached to it.

**Comment by flovilmart** [comment] 2017-03-16 00:53
That.'a where it gets tricky :) I have a branch open on the push adapter that irntoduces a mock connection, that would help us go more E2E testing.

On parse-server, due to the complexity of the project, we follow TDD. The best way to go around that, would be to mock/spy on the apn.connection and validate that we're all good.

**Comment by flovilmart** [comment] 2017-03-16 00:59
the SQS allows to spread the load across your parse-server instances or dedicated push instances (workers) the goal it to make a light PushStatus reporter (that would leverage the JS SDK and not directly parse-server) in order to integrate it easily in the push adapters.

**Comment by jeacott1** [comment] 2017-03-16 01:10
also, if a push query results in zero results, the tracker will also get stuck because it starts but nothing exists to end it.

I've shortcut this in my local copy of ParseQueue with
    if (!results || count==0) {
        return Promise.reject({error: 'PushController: no results in query'});
      }

this breaks a couple of tests in PushController though, but I think its a reasonable solution.

**Comment by felipemobile** [comment] 2017-03-16 09:17
@flovilmart Can you point me in the right direction to help debugging this issue? There are 4 open branches in the adapter. I've tried to downgrade only the adapter to 1.1.0 and also upgrade to 1.3.0. Nothing seems to help.

**Comment by flovilmart** [comment] 2017-03-16 12:05
I'll try to have a look.

**Comment by flovilmart** [comment] 2017-03-16 12:47
Also, I've added the no-babel branch, that is not using babel anymore, can you try with that one?

**Comment by felipemobile** [comment] 2017-03-16 14:17
Same odd issue

`$  sudo npm install https://github.com/parse-server-modules/parse-server-push-adapter.git#no-babel --save`


```
verbose: _PushStatus UN9zhDQOt2: sending push to 1 installations
ERR! parse-server-push-adapter APNS no qualified connections for com.diariodopara 3ac4dbf3bc1c73e2ec2542cb183f3b12e516e38cfccc2a607c64dbe05b45a413
verbose: _PushStatus UN9zhDQOt2: sent push! 0 success, 1 failures
```

**Comment by felipemobile** [comment] 2017-03-16 14:20
@flovilmart Everything seems to be fine on the adapter, maybe 

`npm WARN engine parse-server-push-adapter@1.3.0: wanted: {"node":">= 6.2.0"} (current: {"node":"4.8.0","npm":"2.15.11"}`

I will try to upgrade the node version to 6.2.0.

**Comment by flovilmart** [comment] 2017-03-16 14:21
Yeah removed babel, so we need node 6+ in order to work correctly ;)

**Comment by flovilmart** [comment] 2017-03-16 14:22
But that may be easier to debug inside the node_modules/parse-server-push-adapter as the code is not generated anymore, but clean

**Comment by felipemobile** [comment] 2017-03-16 14:50
@flovilmart First of all, thanks for your help but I need to read more books about node and npm. since this subject is new completely new to me. I'm used to code in objective-c, swift or java (android).

```
$ node -v
v7.6.0
```

**Comment by felipemobile** [comment] 2017-03-18 00:43
@flovilmart I don't give up easily 👍 

Can you give me some advice in how do I override the nested parse-server-push-adapter dependency with my own version?

I've tried to use shrinkwrap but it raises a syntax error.
[npm-shrinkwrap.json.zip](https://github.com/ParsePlatform/parse-server/files/852033/npm-shrinkwrap.json.zip)

```
ParsePushAdapter.js:4
const { classifyInstallations } = require('./PushAdapterUtils');
      ^
SyntaxError: Unexpected token {
```

**Comment by flovilmart** [comment] 2017-03-18 01:00
let me get back to you on that, there à many ways, some trickier than others

**Comment by flovilmart** [comment] 2017-03-18 01:00
For your Error, you should probably try with node 6.9.5+

**Comment by felipemobile** [comment] 2017-03-18 09:44
Ok

```
$ node -v
v7.6.0
```

And it gets better and better

parse-server@2.3.7

```
../node_modules/parse-server/lib/Controllers/AdaptableController.js:93
        throw new Error("Adapter prototype don't match expected prototype", adapter, mismatches);
        ^
Error: Adapter prototype don't match expected prototype
```

**Comment by flovilmart** [comment] 2017-03-18 15:17
Are you using the no-babel branch? I probably messed up the exports :)

**Comment by felipemobile** [comment] 2017-03-18 16:32
Yes, but is parse-server-push adapter@1.3.0 compatible with parse-server@2.3.7?

**Comment by felipemobile** [comment] 2017-03-18 17:41
@flovilmart The latest push-adapter seems to be incompatible with the latest parse-server and I can't help debugging with the current parse-server version. Is it safe to say that we cannot send push messages with the latest Parse-server?

```
/Path/node_modules/parse-server/lib/Controllers/AdaptableController.js:93
        throw new Error("Adapter prototype don't match expected prototype", adapter, mismatches);
        ^

Error: Adapter prototype don't match expected prototype
    at Function.validateAdapter (/Path/node_modules/parse-server/lib/Controllers/AdaptableController.js:93:15)
    at new PushWorker (/Path/node_modules/parse-server/lib/Push/PushWorker.js:64:35)
    at new ParseServer (/Path/node_modules/parse-server/lib/ParseServer.js:296:20)
    at new _ParseServer (/Path/node_modules/parse-server/lib/index.js:48:16)
    at Object.<anonymous> (/Path/index.js:27:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by flovilmart** [comment] 2017-03-18 18:03
We should always have compatibility for those, it's tests in parse-server's unit tests for the core adapters, I'll have a look later today

**Comment by flovilmart** [comment] 2017-03-18 18:53
I updated parse-server-push-adapter#no-babel to make sure tests are OK.

What I did in parse-server repo:

1. clone this repository 
2. edit package.json: 

```
-    "parse-server-push-adapter": "1.3.0",
+    "parse-server-push-adapter": "parse-server-modules/parse-server-push-adapter#no-babel",
```

3. run the tests:

```
npm test
```

To debug your issue you can easily add a unit test to `spec/PushController.spec.js` or `spec/PushWorker.spec.js`

**Comment by jeacott1** [comment] 2017-03-20 00:05
notifications will also get 'stuck', if an installation is added or removed during a push.

**Comment by bjorno** [comment] 2017-03-23 14:10
I'm having the same issue as @felipemobile, where no iOS pushes are being sent. I first noticed it on March 17th, when a push failed, where prior to that day all pushes had succeeded. I am running my app off of the parse-server-example, so I am not sure if I am able to downgrade the server version being used. My parse-server-push-adaptor seems to still be on version 1.1.0. I had not made back end any changes on my end around that time period, so I was not sure why the pushes suddenly stopped working. Any ideas?

**Comment by pvijayen** [comment] 2017-03-24 00:27
Having the same issue, iOS pushes are stuck at "Sending" on the dashboard

**Comment by flovilmart** [comment] 2017-03-24 01:10
I plan to change he way the state is changed from sending to sent in the next release. Perhaps aggressively right after all batches are scheduled. Then, you can check number sent that should properly reflect the counts.

**Comment by felipemobile** [comment] 2017-03-24 20:09
@bjorno You can downgrade your Parse-server to version 2.3.1 and it will work except for a high volume of push messages (80k installations seems to work fine). Please, check the change log for [more info](https://github.com/ParsePlatform/parse-server/blob/master/CHANGELOG.md).

You can downgrade your Parse-server by running the code:
`$ npm install parse-server@2.3.1`

@flovilmart I'm running my own version of the parse-server-example. To give you an example of what I've done you can check the [forked version](https://github.com/Colubris/parse-server-example) where I've updated the parse-server-example to include a config file in json format and a way to run multiple instances of Parse-Server on different ports.

Regarding the push issue, I think the setup function is not being called on the adapter.

**Comment by flovilmart** [comment] 2017-03-24 20:28
I really discourage running multiple parse-server on different ports unless you start multiple node process. the Parse SDK will only be initialized with the last provided AppId.

**Comment by felipemobile** [comment] 2017-03-24 21:01
@flovilmart It's running really fine for more than 20 apps! ;-)

In the parse-server-push-adapter@1.1.0 you were handling all connection callbacks in the APNS.js but in the newest version I can see a huge difference. I will take some time this weekend to check line by line. Unfortunately I did not get a way to debug it yet.
 
   ```
this.conns = [];
   ...
  for (let apnsArgs of apnsArgsList) {
    let conn = new apn.Connection(apnsArgs);
    ...
    // Set apns client callbacks
    conn.on('connected', () => {
      log.verbose(LOG_PREFIX, 'APNS Connection %d Connected', conn.index);
    });
   ...
    this.conns.push(conn);
  }
```

**Comment by flovilmart** [comment] 2017-03-24 22:52
As long as you don't use cloud code......... we know it can somehow look like it work, but it's really dangerous, you may end up saving data in the wrong app, and that I know it for a fact, as a large rejected PR shows

**Comment by bjorno** [comment] 2017-03-26 13:13
@felipemobile That command does not seem to work, maybe because I installed the parse-server by downloading the entire parse-server-example zip file, and then pushed the entire thing to heroku. On my dashboard it just says server version 2.3.7.

**Comment by felipemobile** [comment] 2017-03-26 18:09
@bjorno Maybe you should install by using -g flag, so it will install the package into the global node_modules folder.

`$ npm install -g parse-server@2.3.1`

You can try to clear the cache or remove the folder (rm -rf node_modules): 

`$ npm cache clean`

**Comment by bjorno** [comment] 2017-03-26 22:21
@felipemobile Thanks for the suggestions! I managed to fix the problem when I realised that the real issue was that my .p12 cert had expired, and I never uploaded the renewed one. I appreciate you taking the time to help me though!

**Comment by felipemobile** [comment] 2017-03-27 00:16
@flovilmart running one instance of Parse-server in a single node process seems to solve the push issue however it has a downside when running multiple node process (20x) in a single amazon EC2 t2.micro instance. 

Can you give me an advice? Have you ever implemented a similar architecture?

**Comment by flovilmart** [comment] 2017-03-27 11:21
You should probably scale up this instance, 20 process would require about 4Gb of RAM+. We're running on kubernetes on multiple clusters and AZ's so we have quite a different setup, with different costs too

**Comment by felipemobile** [comment] 2017-03-27 15:10
@flovilmart I scale up to a t2.medium instance and it works however I've found something weird - Pushes are sent to all installations even when I define an audience.

I've created a [shell script](https://github.com/Colubris/parse-server-example/blob/master/colubris_start.sh) that reads the config file and run 'forever' for each instance then I will be able to start or stop each app individually.

**Comment by felipemobile** [comment] 2017-03-31 14:22
@flovilmart Android messages are not counting towards the total so the status is stuck in SENDING state.

**Comment by flovilmart** [comment] 2017-03-31 16:45
uhh that's odd, need to check on the adapter why it doesn't count.

**Comment by felipemobile** [comment] 2017-04-27 14:10
@flovilmart Push Notifications stuck in SENDING state when an installation's deviceToken is set to null. I'm not sure if all push messages after this row are sent or if this bug is happening due to an unhandled exception:

https://github.com/parse-community/parse-server/blob/2533a8cdb316dc9e31ff416af4e37a95f5fbf86e/src/RestWrite.js#L649

I've found some old installations in my _Installation collection without deviceToken and pushType values (March/2015) for both Android and iOS devices.

PS 1: the STATUS changes to SENT when I delete these buggy rows.
PS 2: the push subscriber count shows the right value (1).

**Comment by flovilmart** [comment] 2017-04-27 14:20
We can force exclusion in the initial query so we don't count them nor fail

**Comment by felipemobile** [comment] 2017-04-27 14:27
Nice! I've confirmed that all other push messages are sent and status changes to SENT after deleting all rows with null value set on deviceToken column. 

@flovilmart I swear I tried to find where to fix it :)

**Comment by felipemobile** [comment] 2017-04-27 23:50
Something like this:
`updateWhere["deviceToken"] = {"$exists":true}`

**Comment by flovilmart** [comment] 2017-04-27 23:58
That would be on the where directly, if not set :) updateWhere is only used for the badge updates.
 With the according tests obviously :)

**Comment by felipemobile** [comment] 2017-04-28 00:13
Right, I need a little sleep.

Maybe this code below should help [here](https://github.com/parse-community/parse-server/blob/907b160fc7317b016fc728a1b30ce3d24ead7d73/src/Controllers/PushController.js#L18
). If you agree I can try to write the according tests.

```
var hasDeviceToken = where.hasOwnProperty('deviceToken');
if (!hasDeviceToken) {
  where["deviceToken"] = {"$exists":true}
}
```

**Comment by flovilmart** [comment] 2017-04-28 00:38
Yep, that should do, only if the property is not set :)

**Comment by felipemobile** [comment] 2017-04-28 15:13
@flovilmart the push stuck in sending state only if the property is not set :)

**Comment by flovilmart** [comment] 2017-04-28 15:17
Yep!

**Comment by felipemobile** [comment] 2017-04-28 15:44
I hope the problem will be solved with this pull request :)
https://github.com/parse-community/parse-server/pull/3764

**Comment by cinder92** [comment] 2017-05-16 01:37
is this fixed? i just have same issue, trying sending ios and android push notifications, not sendind to anyone 😢

**Comment by flovilmart** [comment] 2017-05-16 01:41
@cinder92 did you check your configuration? can you provide logs? This issue, involving _PushStatus stuck in sending state would actually get stuck AFTER **sending** and **delivering** the pushes.

**Closed** 2017-05-16 01:42 UTC

**Comment by myusuf3** [comment] 2017-05-25 13:39
@flovilmart  I am in the state as @cinder92 I recently added android and the issue of thing being stuck in send state for several users. 

It was working fine for a couple of days then broke for a certain chunk of users, possibly users who also use android as well. Ideas on what the issue is?

my configuration was working now it just seems to have stopped.

**Comment by LassassinX** [comment] 2020-09-07 23:29
I'm fairly new to development and am using back4app for cloud storage and push notification on android devices only.
I can confirm that pushes that are stuck at "SENDING" never reach the device.
On top of that the response that I get after the sending the reponse is {result : true} which is even more odd as these pushes were not sent out at all. They are stuck in running state.
If at-least the response told me that something was wrong , I could have recorded it in my db and retry the push some other time.

**Comment by LassassinX** [comment] 2020-09-08 11:11
I can confirm that pushes stuck at the sending state never reach the device.
