### ISSUE TITLE
Logging when cloud function result contains base64 image

### ISSUE THREAD

**Issue by mauvesteven** [parse-community/parse-server#3918] opened 2017-06-09 00:43 UTC
Is there a way to turn off logging on a specific cloud function but not for all of them? My issue is that the result of my cloud function contains a base64 image, and Parse Server by default output the base64 string to the log, which makes my daily log files extremely large and hard to maintain.

setting logLevel = 'warn' instead of 'info' solves this problem but then I lost the I/O information of other cloud functions which I also need..

**Comment by acinader** [comment] 2017-06-09 22:07
I wrote a test case see #3919 

Just want to make sure I understand the issue.  

Here's the log out put from this test:

the output of the test for me is:

```
[ { functionName: 'readImageToBase64',
    params: {},
    user: 'FKzEJUaKJ3',
    level: 'info',
add a failing test...
    message: 'Ran cloud function readImageToBase64 for user FKzEJUaKJ3 with:\n  Input: {}\n  Result: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx4BBQUFBwYHDggIDh4UERQeHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHv/CABEIAiYCJgMBIgACEQEDEQH/xAAdAAABBQEBAQEAAAAAAAAAAAADAQIEBQYHAAgJ/9oACAEBAAAAAPm3OMKYriK4jkUj0ZHfVSCul9W+iNjHr4PKI2w0cS8vLGUWW0UfO8I5Gl3pzKijF4jXRF9IbGPE4+eqrxke9z3ecrBpJYD03ZdR65pnjjZ7mXQbHT0F7YWE0p2hicr4pRZ907XzSMcAR3j8xjCB84HFrZJXocKONofKriPir0ntGhtjSSqtLwDtm2kDsrKUc70BVfPnJ4NJXLc6SzmzHxmnM1zAkE0z2cTWbLn2BIxLIgEfMt9K7ZaBsUamJKN8rX/brV95azzIVsTHfNOBq6obyPkWNrc28xxkYNj3JJMeDygTZM2zlkiAsbq0tLS3tZZzeCN8mXM4NnNH0S5uLq2mIjIfHfmygqY5F85XkMaz0eklBOKOVynf4OIRHFJOkEGGRY3N1ZzZc2WZ3nlLzPJ3rpvUr40ie0VP818LgQfE8rfOOR5JEqw0FraMiFWOR7PU7mksvC9JM50mXY2FhYTZcgyoLA4zSkyG76tbuW2j4b5d5tCiFf5Go6QZy+kyTHuNJKAcFNYzG+rZE0ltNNHrY02VLPMlTJ0y6uJ5IHPMWObQ1ez11/ezZ/CfmargCP5vmeIQxDv8dwTz5866sxVUiQwtPPtjw7+xkXtHz315Z2dhsdxqJSt8iei884vl9lZ3mv0md+BYMNp0RgzEV0qewTXGAKbZkm6eyFHIIlIexn2Mq8vtM/LfOOTsuxfUewd5GiRyJ7y... (truncated)',
    timestamp: '2017-06-09T21:27:59.882Z' } ]
```

The message field of the log object is ~1000 characters which is set by [this var]( https://github.com/parse-community/parse-server/blob/e0be653f4ce9a7fc36a45ddc4079775cd7e06cee/src/Controllers/LoggerController.js#L7) in the LoggerController.

So, is my test accurate and the issue is that this log of ~1k char is too long -- which I buy, just making sure?

**Comment by mauvesteven** [comment] 2017-06-10 00:40
yes, this is similar to what I had..

**Comment by acinader** [comment] 2017-06-10 22:55
@flovilmart any thoughts?  I chose 1k char limit to match parse.com.  I don't really see a way to change this for the duration of a function since the logger is shared....

1. make truncation chars configurable.  wont fix it for just one function, but will at least make adjustable?
2. add something to the response object to indicate not to log, or at least to make it really short.

**Comment by flovilmart** [comment] 2017-06-11 13:39
I'm ok with 1, that will help. 
also, we could create a copy of the logger for each http request / response, this way we could use that logger for the cloud code life cycle no? This will let a user reconfigure the logger inside a beforeSave.

**Comment by acinader** [comment] 2017-06-20 16:20
I'm not going to have time to put a bow on this in the next month.  could close or someone else can pick it up?

**Comment by virtualtoy** [comment] 2018-08-16 06:49
@acinader problem is it logs 3 components that can be long: input, result and params:
```
logger.info(`Ran cloud function ${functionName} for user ${userString} with:\n  Input: ${cleanInput }\n  Result: ${cleanResult }`, {functionName, params, user: userString});
```
Input is stringified and trimmed params. Result is trimmed as well, but params is just a raw object which can be huge. Why not remove 3rd parameter completely and log it with verbose level?

**Closed** 2018-10-07 08:35 UTC
Labels: wontfix
