### ISSUE TITLE
Cache grows when not using enableSingleSchemaCache

### ISSUE THREAD

**Issue by flovilmart** [parse-community/parse-server#4247] opened 2017-10-11 21:30 UTC
### Issue Description

It has been observer that the new caching mechanism (LRUCache) would not prune proactively it's cache after a certain amount of time, leading to memory growth and explosion.

### Steps to reproduce

- Startup a parse-server, without enableSingleSchemaCache
- use heapdump through `require('heapdump')` in your startup script
- notice that the memory keeps growing after each request.

#### Expected Results

Memory usage should somewhat remain constant, unused data should not be kept indefinitely.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : >= 2.5.1
  - Operating System:     n/a
  - Hardware:            n/a
  - Localhost or remote server? local

- **Database**
  - MongoDB version: n/a
  - Storage engine:  n/a
  - Hardware:        n/a
  - Localhost or remote server? n/a
### Logs/Trace

See discussion over: https://github.com/parse-community/parse-server/issues/4235

Suggested resolution:

1- make singleSChemaCache default (this should be pretty harmless)
2- actively cleanup upon response end the schema cache used for the request
3- actively prune LRU cache dropping older values periodically

**Comment by alvajindia** [comment] 2017-11-23 14:40
@flovilmart any updates on this issue ? Still looking for someone to take this up ? The label good first issue is tempting me if you can give some courage

**Comment by flovilmart** [comment] 2017-11-23 14:43
Yes that should be an easy one, the suggested resolution should be solid at the moment, and  it will give you a good insight on the underskirts of parse-server :)

If you run into any issue, just let me know!

**Comment by cyrixmorten** [comment] 2017-11-30 12:48
Can confirm that setting `enableSingleSchemaCache: true` effectively stops the memory consumption from growing.

Exceeded my memory quota on Heroku this morning and after setting the boolean it has been steady at ~100mb

![screen shot 2017-11-30 at 13 43 14](https://user-images.githubusercontent.com/6650168/33431511-e0e362e0-d5d4-11e7-9eda-67e27041df02.png)

**Comment by montymxb** [comment] 2017-12-02 02:20
Yeah we need to address this. I took a look at some of the code at one point. Haven't confirmed it but it does just seem to be a bad case of not cleaning up the multitude of schema caches that accumulate over time. Interesting code being [here](https://github.com/parse-community/parse-server/blob/master/src/Controllers/SchemaCache.js#L11...L21) in **SchemaCache.js**. Over time with random prefix ids I imagine you could fill up memory no sweat. One way would be to track formerly used caches (particularly stale?) and flush those after a certain count. Maybe a cache of existing cache prefixes that still exist so we can keep track of them?

**Comment by flovilmart** [comment] 2017-12-02 03:25
The issue is that:
1- we don’t cleanup the cache / request after the request is over
2- The LRUCache don’t actively prune

We could manually prune the cache just after each requests or periodically, and/or when the request is over; remove the key associated in the cache with it.

**Comment by NicksonYap** [comment] 2018-05-21 17:27
Any fix for this so far?
Does `enableSingleSchemaCache: true` affect anything?

**Comment by NicksonYap** [comment] 2018-05-21 17:29
I suppose a reduced cache size = reduced performance?

**Comment by flovilmart** [comment] 2018-05-21 17:33
Nope increased performance. But may yield issues if multiple Schema mutations are run concurrently

**Comment by JacobJT** [comment] 2018-05-21 18:13
The _Schema query has been in our slow queries tab on mLab for a while. Will setting this affect the number of _Schema queries, or only the memory due to caching the results?

**Comment by flovilmart** [comment] 2018-05-21 18:31
Yes that’s what it’s meant for

**Comment by fayyadsufyan** [comment] 2018-05-31 18:29
I can confirm that setting the enableSingleSchemaCache to true fixes the memory issue and stabilize the RAM usage between 90-150 MB.
Check the screenshot and notice the highlighted area.

Parse 2.7.1
Ubuntu 16.04

![parse-01](https://user-images.githubusercontent.com/36089616/40800361-7bf52438-6510-11e8-92f8-04cdb5125221.PNG)

**Comment by dplewis** [comment] 2019-07-10 19:42
Closing via https://github.com/parse-community/parse-server/pull/5612

**Closed by dplewis** 2019-07-10 19:42 UTC
Labels: good first issue, hacktoberfest, help wanted
