### ISSUE TITLE
Error "id is an invalid field name" in Parse server 3.x

### ISSUE THREAD

**Issue by manhhavu** [parse-community/parse-server#6309] opened 2019-12-31 12:42 UTC
# Before opening the issue please ensure that you have:

- [x] [Read the migration guide](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) to parse-server 3.0.0
- [x] [Read the migration guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md) to Parse SDK JS 2.0.0

### Issue Description

Saving an object with a "id" field causes error: "id is an invalid field name."

Note: I'm using 2.x version in production. The saving works very well until 2.8.4. When I try to migrate 3.x, I've encountered this error which blocks the migration because I have many classes having "id" fields in my application.

### Steps to reproduce

1. Open Parse Dashboard 
    2. Create a class, ex: TestClass
    3. In REST console, make a POST request to TestClass

```json
{ "id": "A125" }
```
 
### Expected Results

```json
{
    "success": {
      "objectId": "3S8aY2gwZo",
      "createdAt": "2019-12-31T12:36:16.733Z"
    }
}
```

### Actual Outcome

```json
{
    "code": 105,
    "error": "id is an invalid field name."
}
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.0.0, 3.4.4, 3.9.0
  - Operating System:    macOS
  - Hardware:             Macbook Pro
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: -
  - PostgreSQL version: 11.2
  - Storage engine:  PostgreSQL
  - Hardware:        Macbook Pro
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

**Comment by memishood** [comment] 2020-01-05 19:46
i recommend that you should use different name for id because it is used by mongodb

**Comment by memishood** [comment] 2020-01-05 19:46
i recommend that you should use different name for id because it is used by database

**Comment by dplewis** [comment] 2020-01-05 22:39
There are also other side effects to using `id` field, which is why we don't allow the use of `id`.

See https://github.com/parse-community/parse-server/pull/5664/files

Closing as this is expected behavior.

*Note* If you want to use id / objectId to create your own objectId's this will be a feature in the next release.

**Closed by dplewis** 2020-01-05 22:39 UTC

**Comment by iyashamihsan** [comment] 2021-01-28 13:32
> i recommend that you should use different name for id because it is used by database

its worked
