### ISSUE TITLE
Username/email uniqueness is case-sensitive

### ISSUE THREAD

**Issue by rihadavid** [parse-community/parse-server#3990] opened 2017-07-03 16:24 UTC
### Issue Description

Let's say there is a User with username elonmusk and email elon@musk.com.
The problem is, that another user can create another account, with username ElonMusk and email Elon@Musk.com.

**The username uniqueness case-sensitivity** might be a feature, not a bug, I don't know. But I think it should be case insensitive. For example, twitter.com/elonmusk is the same Musk as twitter.com/ElonMusk and this is how it works on most apps, I think.

However, **the email uniqueness case-sensitivity** is obviously a bug, because elon@musk.com and Elon@Musk.com is the same email address, which means that more users can have the same email, which means it is not unique.

### Steps to reproduce

Just create two Users in the dashboard and try filling the same email/username. It throws an error. Now try with different capitalization. It works.

#### Expected Results

When defining username or email field, it should check that there is no user with the same username or email, regardless of letters capitalization.

#### Actual Outcome

It allows creating another user with the same username/email, just different letter capitalization.

### Environment Setup

- **Server**
  - parse-server version: 2.5.3
  - Operating System: WINDOWS
  - Localhost or remote server: LOCAL

- **Database**
  - MongoDB: MLAB.COM

Maybe @drew-gross could be interested in this issue?

Thanks!

**Comment by flovilmart** [comment] 2017-07-03 22:39
We should probably lowercase it all! Not sure how it was implemented in parse.com. We could also simply update the queries for case insensitive comparison. What would you prefer?

**Comment by montymxb** [comment] 2017-07-03 23:28
Just a note it's not _completely_ guaranteed that the local part (before the @) is case insensitive. A quick mention of this is in this [so post](https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive).

This is more just a thing to be aware of though. It's generally better practice to just lower case them all, since pretty much all addresses are case insensitive nowadays. It's kind of a weird situation but I would be on the side of it's 'safe to assume' that most are case insensitive.

**Comment by flovilmart** [comment] 2017-07-04 00:27
So moving forward, the resolution is 3 fold:

1. make all queries with regexp case insensitive for username and email
2. make all emails fields always lowercase in read / write operation
3. find a solution for the username? Store as is, but query with 1?

**Comment by sirnacnud** [comment] 2017-11-25 17:44
What is the status on this issue? I actually had a user create two accounts with the same email and username, but the case is different. This is fairly easy to do when the keyboard automatically capitalizes the first letter on text input fields (iOS does this).

**Comment by montymxb** [comment] 2017-11-25 23:43
@sirnacnud We haven't been working on this lately. Although it is something we are still aware of, we're focusing on other issues at the moment. That being said we are always open to someone taking the initiative and putting up a PR. We can always help guide things from there.

**Comment by JacobJT** [comment] 2018-04-30 23:00
We've had some issues with password resetting based on case-sensitivity. We use the e-mail as the username, as well, but force it to lower case to maintain uniqueness. We left the e-mail alone as we did not know if it is really safe to tamper with what is entered.  It seems that's a fairly acceptable solution, though? I think the case sensitive e-mail field we currently have affects more people than would be affected by casting to lower case.  

Or should we store as input by the user and expect an eventual update that queries case insensitively?

**Comment by gnu-lorien** [comment] 2018-08-04 17:14
I continue to be affected by this issue. Interestingly part of how I realized that it was a case sensitivity issue is because parse dashboard searches fields in a case insensitive manner.

**Comment by flovilmart** [comment] 2018-08-04 17:15
We laid out a plan for the fix but didn’t get a chance to provide it. Are you willing to give a PR for it?

**Comment by macklus** [comment] 2018-09-03 17:29
Complex problem, sadly.

First, i just apply .toLowerCase() on all users, before save it. Users complain ¿...?
Second, i use query.matches('username', username, 'i'), but its to slow.
Finally, only functional option is set username_lc to username.toLowerCase() and use it to search with equals.

**Comment by flovilmart** [comment] 2018-09-03 17:30
First we can make all queries case insensitive, I’m not for storing additional data

**Comment by macklus** [comment] 2018-09-03 18:03
@flovilmart sure it is better solution than mine. 
I just comment my scenario and how i solve it, just for info if any can use it before PR fix.

**Comment by farhansyed9** [comment] 2018-09-14 20:53
Is there a way to currently achieve this?

**Comment by rolandvar** [comment] 2018-09-17 10:35
> So moving forward, the resolution is 3 fold:
> 
> 1. make all queries with regexp case insensitive for username and email
> 2. make all emails fields always lowercase in read / write operation
> 3. find a solution for the username? Store as is, but query with 1?

Another solution could be give the possibility to enable the mongodb [unique index](https://docs.mongodb.com/manual/core/index-unique/) on the email field, what do you think about it?

**Comment by flovilmart** [comment] 2018-09-17 11:08
The email is already unique and sparse, the problem is the case sensitivity.

**Comment by georgesjamous** [comment] 2018-09-17 11:34
It doesn't make sense to have emails with capitalized letters as they do not matter in an email address.
I believe performing a case-insensitive query to validate emails is just masking the real problem, which is _"Failing to properly store email addresses"_ (in lowercased letters, as they should be).

Forcing all emails to be lowercased is far better than using a case-insensitive query, in speed and an overhaul database consistency.

Developers with existing users should probably migrate all account emails to lowercase and use and use a beforeSave hook to patch this untill a pull request kicks in.

**Comment by flovilmart** [comment] 2018-09-17 11:41
> doesn't make sense to have emails with capitalized letters as they do not matter in an email address.

that’s your opinion, I believe if a dev wants to perform sanitation/ lowercase etc... this can and should be done in a hook.

In the end. I’m not sure we should perform anything on the database indexation side. 

Mixed case usernames can be a feature one developer want. 

Overall, as no one is picking this up for implementation, workarounds are available (through hooks), i’ll be closing.

If one wish to implement one of the suggested resolutions, feel free to open a PR.

**Comment by acinader** [comment] 2019-06-04 20:23
on mongo, in addition to @flovilmart's suggestions, we should also add a case insensitive unique index  to ensure.  not sure if there is the same thing on

**Comment by acinader** [comment] 2019-06-04 22:00
A failing test to get started.

I am not sure how to handle OAuth connected users (and anonymous) which will need to allow usernames that would be a duplicate if evaluated case-insensitively.

I'm gonna get started on how I would handle in a before save hook.  Any input greatly appreciated ;).

**Comment by acinader** [comment] 2019-06-05 00:23
I've just pushed a solution to the failing test.

I'm going to discuss it on the PR, so see #5634 

@flovilmart if you've got the bandwidth, I'd love a guest pr

**Comment by flovilmart** [comment] 2019-06-05 11:39
I don’t have any bandwidth, sorry 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2020-02-14 17:44 UTC
Labels: help wanted, up for grabs
