### ISSUE TITLE
REST API relation updates not working

### ISSUE THREAD

**Issue by Erik-Stevens** [parse-community/parse-server#5589] opened 2019-05-14 01:06 UTC
### Issue Description
Firstly, I'm using a Psql database, not Mongo.
I need to use the REST API to update data in a relation, but it's not working. I'm sending a request and getting a success response from Parse server, not an error. Yet the relation in my database is not updating with the new data. I get the same behavior from AddRelation and RemoveRelation. I also tried a non-existent operation: "FakeRelation" and I still do not get an error returned, just the same success response.

### Steps to reproduce

Here is the http request that I am sending:

```
$.ajaxSetup({
    headers: {
        'X-Parse-Application-Id': hidden,
        'X-Parse-REST-API-Key': hidden,
        'Content-Type': 'application/json',
        'X-Parse-Session-Token': parseToken
    },
});

 $http( {
  method: 'PUT',
  url: '/parse/classes/Departures/' + dep.id,
  data: {
    "staff":{
		"__op":"AddRelation",	
"objects": [{"__type":"Pointer","className":"Employee","objectId":"CUyT69sUu8"},{"__type":"Pointer","className":"Employee","objectId":"ETXBhfyzAz"},{"__type":"Pointer","className":"Employee","objectId":"oBrQyMB1YC"},{"__type":"Pointer","className":"Employee","objectId":"ERxY6XaHYQ"}]
	}
  }
})
```
 
### Expected Results

Parse server should update the existing relation and send a success response with updatedAt and an objectId.

### Actual Outcome

I'm getting a success response from Parse server, but the relation in my database is not updating. The response contains updatedAt, but no objectId. Interestingly the updatedAt value on this object is updating, just not the relation data that it's supposed to update.

### Environment Setup

- **Server**
 parse-server version (Be specific! Don't say 'latest'.) : 3.1.1
Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
Heroku PostgresSQL

**Comment by davimacedo** [comment] 2019-05-14 02:54
Hi. I tried to write a test case in order to reproduce the problem, but my test actually succeeded.

I don't know exactly what you are doing differently, but could you try to send the headers in the requests? Something like this:
```
$http( {
  method: 'PUT',
  url: '/parse/classes/Departures/' + dep.id,
  data: {
    "staff":{
		"__op":"AddRelation",	
"objects": [{"__type":"Pointer","className":"Employee","objectId":"CUyT69sUu8"},{"__type":"Pointer","className":"Employee","objectId":"ETXBhfyzAz"},{"__type":"Pointer","className":"Employee","objectId":"oBrQyMB1YC"},{"__type":"Pointer","className":"Employee","objectId":"ERxY6XaHYQ"}]
	}
  },
  headers: {
        'X-Parse-Application-Id': hidden,
        'X-Parse-REST-API-Key': hidden,
        'Content-Type': 'application/json',
        'X-Parse-Session-Token': parseToken
    },
})
```

If your problem persists, can you please try to write a test case to reproduce the problem? Please find below the one I wrote so you can use as a reference.
```
it('simple add and remove relation through API', async () => {
    const req = require('../lib/request');

    const user = new Parse.User();
    user.setUsername('someusername');
    user.setPassword('somepassword');
    await user.signUp();

    const headers = {
      'Content-Type': 'application/json',
      'X-Parse-Application-Id': 'test',
      'X-Parse-REST-API-Key': 'rest',
      'X-Parse-Session-Token': user.getSessionToken(),
    };

    const childResponse1 = await req({
      method: 'POST',
      url: 'http://localhost:8378/1/classes/ChildClass',
      body: {
        someChildField: 'someChildValue1',
      },
      headers,
    });
    expect(childResponse1.status).toEqual(201);

    const childResponse2 = await req({
      method: 'POST',
      url: 'http://localhost:8378/1/classes/ChildClass',
      body: {
        someChildField: 'someChildValue2',
      },
      headers,
    });
    expect(childResponse2.status).toEqual(201);

    const parentResponse = await req({
      method: 'POST',
      url: 'http://localhost:8378/1/classes/ParentClass',
      body: {
        someParentField: 'someParentValue',
      },
      headers,
    });
    expect(parentResponse.status).toEqual(201);

    const addRelationResponse = await req({
      method: 'PUT',
      url: `http://localhost:8378/1/classes/ParentClass/${
        parentResponse.data.objectId
      }`,
      body: {
        children: {
          __op: 'AddRelation',
          objects: [
            {
              __type: 'Pointer',
              className: 'ChildClass',
              objectId: childResponse1.data.objectId,
            },
            {
              __type: 'Pointer',
              className: 'ChildClass',
              objectId: childResponse2.data.objectId,
            },
          ],
        },
      },
      headers,
    });
    expect(addRelationResponse.status).toEqual(200);

    const parentQuery = new Parse.Query('ParentClass');
    const parentObject = await parentQuery.get(parentResponse.data.objectId);
    let children = await parentObject
      .relation('children')
      .query()
      .find();
    expect(children.map(child => child.get('someChildField')).sort()).toEqual([
      'someChildValue1',
      'someChildValue2',
    ]);

    const removeRelationResponse1 = await req({
      method: 'PUT',
      url: `http://localhost:8378/1/classes/ParentClass/${
        parentResponse.data.objectId
      }`,
      body: {
        children: {
          __op: 'RemoveRelation',
          objects: [
            {
              __type: 'Pointer',
              className: 'ChildClass',
              objectId: childResponse1.data.objectId,
            },
          ],
        },
      },
      headers,
    });
    expect(removeRelationResponse1.status).toEqual(200);

    children = await parentObject
      .relation('children')
      .query()
      .find();
    expect(children.map(child => child.get('someChildField')).sort()).toEqual([
      'someChildValue2',
    ]);

    const removeRelationResponse2 = await req({
      method: 'PUT',
      url: `http://localhost:8378/1/classes/ParentClass/${
        parentResponse.data.objectId
      }`,
      body: {
        children: {
          __op: 'RemoveRelation',
          objects: [
            {
              __type: 'Pointer',
              className: 'ChildClass',
              objectId: childResponse2.data.objectId,
            },
          ],
        },
      },
      headers,
    });
    expect(removeRelationResponse2.status).toEqual(200);

    children = await parentObject
      .relation('children')
      .query()
      .find();
    expect(children.length).toEqual(0);
  });
```

**Comment by Erik-Stevens** [comment] 2019-05-14 22:43
Thanks. Below is a test that I just ran. The first case tries to update a relation and the second case tries to update a simple Number field.  Both cases give Success and updated at, but do not update the data in the DB with the new value. I even added a few more tests to try to change fields in other classes that I know work using the REST API through X-editable. But I get the same result. There's something about the requests below that doesn't work. Whatever request X-editable is sending DOES work, but I don't know how to view that request to compare it. I'm pretty sure it's using the same headers, url, and body format. I'm stuck. What's wrong with these requests?

`//gives Success! and updatedAt, but does not update the data in DB
$.ajax({
		  type: 'PUT',
		  //dataType: 'json', // Set datatype - affects Accept header
		  headers: {
				'X-Parse-Application-Id': hidden,
				'X-Parse-REST-API-Key': hidden,
				'Content-Type': 'application/json',
				//"X-HTTP-Method-Override": "PUT", // X-HTTP-Method-Override set to PUT.
				'X-Parse-Session-Token': parseToken
			},
		  url: '/parse/classes/Departures/9GpdfMVh8Q',
		 body: {"staff":{"__op":"AddRelation","Objects":[{"__type":"Pointer","className":"Employee","objectId":"CUyT69sUu8"}]}},
		success: function successCallback(response) {
    // this callback will be called asynchronously
    // when the response is available
	alert("Success!  "+response.objectId + ", updated at: " +  response.updatedAt);
  },
		error: function successCallback(response) {
    // this callback will be called asynchronously
    // when the response is available
	alert("Error!  "+response.objectId + ", updated at: " +  response.updatedAt);
  }
	
  });
  
  
  //gives Success! and updatedAt, but does not update the data in DB
  $.ajax({
		  type: 'PUT',
		  //dataType: 'json', // Set datatype - affects Accept header
		  headers: {
				'X-Parse-Application-Id': hidden,
				'X-Parse-REST-API-Key': hidden,
				'Content-Type': 'application/json',
				//"X-HTTP-Method-Override": "PUT", // X-HTTP-Method-Override set to PUT.
				'X-Parse-Session-Token': parseToken
			},
		  url: '/parse/classes/Departures/dGD9zOZA7w',
		 body: {"maxpax":1234},
		success: function successCallback(response) {
    // this callback will be called asynchronously
    // when the response is available
	alert("Success!  "+response.objectId + ", updated at: " +  response.updatedAt);
  },
		error: function successCallback(response) {
    // this callback will be called asynchronously
    // when the response is available
	alert("Error!  "+response.objectId + ", updated at: " +  response.updatedAt);
  }
	
  });`

**Comment by davimacedo** [comment] 2019-05-14 23:15
I think $.ajax does not have "body" option. You should use "data" instead. Also, in the first example, it should be "objects" instead of "Objects". Can you please try again?

**Comment by Erik-Stevens** [comment] 2019-05-14 23:28
When I try "data" I get error 400 Bad Request back from Parse server.
Switching 'Objects' to 'objects' made no difference. Nice catch though.

**Comment by Erik-Stevens** [comment] 2019-05-14 23:38
Just checked the server logs and all it reports is status=200 on this put request.

**Comment by davimacedo** [comment] 2019-05-15 00:07
Try “data: JSON.stringify({ ... })”

**Comment by Erik-Stevens** [comment] 2019-05-15 00:59
Thanks! That worked for my test cases. I had tried “body: JSON.stringify({ ... })” but not “data: JSON.stringify({ ... })”

Now I just need to figure out how to make X-editable send the correct JSON for a relation. That still isn't working for me. 

As for Parse Server, it seems buggish that it was responding with Status 200 (Success) even though the JSON was mal-formed and the DB didn't update. Seems like it really should give an error here, preferably one that says something about the JSON being wrong. Would have saved me hours of troubleshooting.

**Comment by davimacedo** [comment] 2019-05-15 20:50
I've just tested here and the server responds a 400 error if you send an invalid JSON. In your previous tests, the server was either receiving nothing or an empty object. In these cases, it updates only the updatedAt of the object (since there is no other fields to update in the request), succeeds the operation with code 200 and returns the updated fields (in this case, only the updatedAt). I'm closing the issue since it is not a Parse Server bug. For X-editable, I suggest you to send a question in Stackoverflow.

**Closed by davimacedo** 2019-05-15 20:50 UTC
